# Generated by Django 4.2.11 on 2024-03-07 01:53

from django.db import migrations, models
from django.forms.models import model_to_dict
import djongo.models.fields


def migrate_darwin_access_controls(apps, schema_editor):
    DarwinAccessControlModel = apps.get_model("darwin", "AccessControl")
    SecurityAccessControlModel = apps.get_model("security", "AccessControl")
    db_alias = schema_editor.connection.alias
    DarwinAccessControls = DarwinAccessControlModel.objects.using(db_alias)
    SecurityAccessControls = SecurityAccessControlModel.objects.using(db_alias)

    for acl in DarwinAccessControls.all():
        new_acl = SecurityAccessControls.create(
            **model_to_dict(acl, exclude=['_id'])
        )
        for wacl in acl.workflowacl_set.all():
            wacl.access_control_id = new_acl.pk
            wacl.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='Friendly name', max_length=255, unique=True, verbose_name='Friendly name')),
                ('acls', models.TextField(default='')),
                ('rules', djongo.models.fields.JSONField(default=list)),
            ],
        ),
        migrations.RunPython(migrate_darwin_access_controls, migrations.RunPython.noop),
    ]
