# Generated by Django 2.1.3 on 2019-04-01 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('darwin', '0001_initial'),
        ('applications', '0003_auto_20190401_0758'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fqdn', models.TextField(default='www.example.com', help_text='Public name')),
                ('public_dir', models.TextField(default='/', help_text='Directory on which apply the conf')),
                #('access_control_list', models.ForeignKey(help_text='Access control list', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.AccessControl')),
                ('authentication', models.ForeignKey(help_text='User authentication', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.UserAuthentication')),
                ('backend', models.ForeignKey(help_text='Backend', on_delete=django.db.models.deletion.CASCADE, to='applications.Backend')),
                #('darwin_policy', models.ForeignKey(help_text='Darwin Policy', null=True, on_delete=django.db.models.deletion.SET_NULL, to='darwin.DarwinPolicy')),
                ('frontend', models.ForeignKey(help_text='Frontend', on_delete=django.db.models.deletion.CASCADE, to='services.Frontend')),
            ],
        ),
        # migrations.AlterUniqueTogether(
        #     name='workflow',
        #     unique_together={('frontend', 'fqdn', 'public_dir')},
        # ),
    ]
