# Generated by Django 2.1.3 on 2019-04-01 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20190401_0838'),
        ('services', '0003_auto_20190401_0838'),
        ('authentication', '0001_initial'),
        ('darwin', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='backend',
            field=models.ForeignKey(help_text='Backend', on_delete=django.db.models.deletion.PROTECT, to='applications.Backend'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='fqdn',
            field=models.TextField(help_text='Public name'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='frontend',
            field=models.ForeignKey(help_text='Frontend', on_delete=django.db.models.deletion.PROTECT, to='services.Frontend'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='public_dir',
            field=models.TextField(help_text='Directory on which apply the conf'),
        ),
        # migrations.AlterUniqueTogether(
        #     name='workflow',
        #     unique_together={('frontend', 'access_control_list', 'darwin_policy', 'backend'), ('frontend', 'fqdn', 'public_dir')},
        # ),
    ]
