# Generated by Django 2.1.3 on 2019-08-29 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20190829_1041'),
        ('applications', '0008_auto_20190829_1041'),
        ('darwin', '0006_auto_20190829_1041'),
        ('workflow', '0002_auto_20190401_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='defender_policy',
            field=models.ForeignKey(help_text='Defender Policy', null=True, on_delete=django.db.models.deletion.PROTECT, to='darwin.DefenderPolicy'),
        ),
        # migrations.AlterField(
        #     model_name='workflow',
        #     name='access_control_list',
        #     field=models.ForeignKey(help_text='Access control list', null=True, on_delete=django.db.models.deletion.SET_NULL, to='darwin.AccessControl'),
        # ),
        # migrations.AlterUniqueTogether(
        #     name='workflow',
        #     unique_together={('frontend', 'fqdn', 'public_dir'), ('frontend', 'access_control_list', 'defender_policy', 'backend')},
        # ),
    ]
