# Generated by Django 2.1.3 on 2019-09-04 16:04

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_auto_20190829_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowACL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('action_satisfy', models.TextField()),
                ('action_not_satisfy', models.TextField()),
                ('redirect_url_satisfy', models.TextField()),
                ('redirect_url_not_satisfy', models.TextField()),
                ('before_policy', models.BooleanField(default=True)),
                ('access_control', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='darwin.AccessControl')),
            ],
        ),
        migrations.AddField(
            model_name='workflow',
            name='name',
            field=models.TextField(default='', help_text='Friendly name'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='workflow_json',
            field=djongo.models.fields.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='defender_policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='darwin.DefenderPolicy'),
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='authentication',
        ),
        migrations.AlterUniqueTogether(
            name='workflow',
            unique_together={('frontend', 'fqdn', 'public_dir', 'backend')},
        ),
        migrations.AddField(
            model_name='workflowacl',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Workflow'),
        ),
    ]
