# Generated by Django 3.0.5 on 2021-07-01 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20210615_1732'),
        ('workflow', '0005_workflow_authentication'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='authentication_filter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='authentication.AuthAccessControl'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='authentication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='authentication.UserAuthentication'),
        ),
    ]
