# Generated by Django 4.2.6 on 2023-11-15 10:28

from django.db import migrations, models
import djongo.models.fields

def set_default_cors_allowed_methods(apps, schema_editor):
    workflow_model = apps.get_model("workflow", "workflow")
    db_alias = schema_editor.connection.alias
    workflows = workflow_model.objects.using(db_alias)

    for workflow in workflows.all():
        workflow.cors_allowed_methods = ["*"]
        workflow.save()

class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_remove_workflow_defender_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='cors_allowed_headers',
            field=models.TextField(blank=True, default='*', help_text='Headers field allowed in the request', verbose_name='Allowed headers'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='cors_allowed_methods',
            field=djongo.models.fields.JSONField(blank=True, choices=[('*', 'All'), ('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('CONNECT', 'CONNECT'), ('OPTIONS', 'OPTIONS'), ('TRACE', 'TRACE')], default=['*'], help_text='Restrict requests to provided methods', verbose_name='Allowed methods'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='cors_allowed_origins',
            field=models.TextField(blank=True, default='*', help_text='Origins allowed to handle the response', verbose_name='Allowed origins'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='cors_max_age',
            field=models.PositiveIntegerField(blank=True, default=600, help_text='Maximum number of seconds the results can be cached', verbose_name='Max age'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='enable_cors_policy',
            field=models.BooleanField(default=False, help_text='Switch to enable specified CORS policy', verbose_name='Enable CORS policy'),
        ),
        migrations.RunPython(set_default_cors_allowed_methods, migrations.RunPython.noop),
    ]
