# Generated by Django 2.1.3 on 2019-04-01 08:38

import django.core.validators
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20190401_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontend',
            name='timeout_client',
            field=models.PositiveIntegerField(default=2, help_text='HTTP request Timeout', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3600)], verbose_name='Timeout'),
        ),
        migrations.AlterField(
            model_name='listener',
            name='max_rate',
            field=models.PositiveIntegerField(default=1000, help_text='Max number of new connexions per source per second.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='listener',
            name='max_src',
            field=models.PositiveIntegerField(default=10, help_text='Max number of connexions per source.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
