# Generated by Django 2.1.3 on 2019-05-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20190401_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='disable_octet_counting_framing',
            field=models.BooleanField(default=False, help_text="Enable option 'SupportOctetCountedFraming' in rsyslog (advanced)."),
        ),
        migrations.AddField(
            model_name='frontend',
            name='enable_logging_body',
            field=models.BooleanField(default=False, help_text='Log body and headers to build Defender dataset from logs.'),
        ),
    ]
