# Generated by Django 2.1.3 on 2019-05-10 15:34

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_zfs'),
        ('services', '0004_auto_20190506_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Openvpn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('remote_server', models.TextField(default='')),
                ('remote_port', models.PositiveIntegerField(default=443)),
                ('proto', models.TextField(choices=[('tcp', 'TCP')], default='tcp')),
                ('status', models.TextField(default='WAITING')),
                ('tunnels_status', djongo.models.fields.DictField(default={})),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.Node')),
                ('tls_profile', models.ForeignKey(help_text='TLS Profile to use.', on_delete=django.db.models.deletion.CASCADE, to='system.TLSProfile')),
            ],
        ),
    ]
