# Generated by Django 2.1.3 on 2019-08-29 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('darwin', '0006_auto_20190829_1041'),
        ('system', '0006_config_logs_ttl'),
        ('services', '0008_auto_20190716_1517'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VulturedSettings',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='enable_impcap_darwin_dns',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='impcap_darwin_dns_filter',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='stock_logs_locally',
        ),
        migrations.AddField(
            model_name='frontend',
            name='darwin_policy',
            field=models.ForeignKey(help_text='Darwin policy to use', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='frontend_set', to='darwin.DarwinPolicy'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='file_path',
            field=models.TextField(default='/var/log/darwin/alerts.log', help_text='Local file path to listen on'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='node',
            field=models.ForeignKey(default=None, help_text='Vulture node', null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Node'),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='https_redirect',
            field=models.BooleanField(default=False, help_text='Redirect http requests to https, if available', verbose_name='Redirect HTTP to HTTPS'),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='impcap_filter_type',
            field=models.TextField(choices=[('udp and port 53', 'DNS'), ('tcp[13] & 2 != 0', 'SYN FLAGS'), ('tcp and (port 80 or port 443)', 'WEB'), ('custom', 'Custom')], default='udp and port 53', help_text='Simple filters used by impcap', verbose_name='Impcap filter type'),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='listening_mode',
            field=models.TextField(choices=[('udp', 'UDP'), ('tcp', 'TCP'), ('tcp,udp', 'TCP & UDP'), ('relp', 'RELP (TCP)'), ('file', 'FILE')], default='tcp', help_text='TCP mode = HAProxy, UDP mode = Rsyslog'),
        ),
    ]
