# Generated by Django 2.1.3 on 2019-09-12 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20190829_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsyslogdarwinsettings',
            name='log_forwarders',
        ),
        migrations.AlterField(
            model_name='listener',
            name='frontend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Frontend'),
        ),
        migrations.DeleteModel(
            name='RsyslogDarwinSettings',
        ),
    ]
