# Generated by Django 2.1.3 on 2019-09-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20190912_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontend',
            name='enable_logging_body',
        ),
    ]
