# Generated by Django 2.1.3 on 2020-03-09 11:28

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20191119_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='akamai_access_token',
            field=models.TextField(default='', help_text='Akamai Access Token'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='akamai_client_secret',
            field=models.TextField(default='', help_text='Akamai Client Secret'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='akamai_client_token',
            field=models.TextField(default='', help_text='Akamai Client Token'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='akamai_config_id',
            field=models.TextField(default='', help_text='Akamai Config Id'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='akamai_host',
            field=models.TextField(default='', help_text='Akamai Host'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='api_parser_type',
            field=models.TextField(default='', help_text='API Parser Type'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='api_parser_use_proxy',
            field=models.BooleanField(default=False, help_text='Use Proxy'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='aws_access_key_id',
            field=models.TextField(default='', help_text='AWS Access Key ID'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='aws_bucket_name',
            field=models.TextField(default='', help_text='AWS Bucket Name'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='aws_secret_access_key',
            field=models.TextField(default='', help_text='AWS Secret Access Key'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='elasticsearch_auth',
            field=models.BooleanField(default=False, help_text='Authentication Elasticsearch'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='elasticsearch_host',
            field=models.TextField(default='', help_text='Elasticsearch URL'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='elasticsearch_index',
            field=models.TextField(default='', help_text='Index to poll'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='elasticsearch_password',
            field=models.TextField(default='', help_text='Elasticsearch password'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='elasticsearch_username',
            field=models.TextField(default='', help_text='Elasticsearch username'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='elasticsearch_verify_ssl',
            field=models.BooleanField(default=True, help_text='Verify SSL'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='forcepoint_host',
            field=models.TextField(default='', help_text='Forcepoint URL'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='forcepoint_password',
            field=models.TextField(default='', help_text='Forcepoint Password'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='forcepoint_username',
            field=models.TextField(default='', help_text='Forcepoint Username'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='last_api_call',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AddField(
            model_name='frontend',
            name='office365_client_id',
            field=models.TextField(default='', help_text='Office 365 Client ID'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='office365_client_secret',
            field=models.TextField(default='', help_text='Office 365 Client Secret'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='office365_tenant_id',
            field=models.TextField(default='', help_text='Office 365 Tenant ID'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='symantec_password',
            field=models.TextField(default='', help_text='Symantec Password'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='symantec_username',
            field=models.TextField(default='', help_text='Symantec Username'),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='listening_mode',
            field=models.TextField(choices=[('udp', 'UDP'), ('tcp', 'TCP'), ('tcp,udp', 'TCP & UDP'), ('relp', 'RELP (TCP)'), ('file', 'FILE'), ('api', 'API CLIENT')], default='tcp', help_text='TCP mode = HAProxy, UDP mode = Rsyslog'),
        ),
    ]
