# Generated by Django 2.1.3 on 2020-04-10 14:20

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20200309_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='keep_source_fields',
            field=djongo.models.fields.JSONField(default={}),
        ),
    ]
