# Generated by Django 2.1.3 on 2020-04-10 14:20

import django.core.validators
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20200309_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='keep_source_fields',
            field=djongo.models.fields.JSONField(default={}, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='keep_source_fields',
            field=djongo.models.fields.JSONField(default={}),
        ),
    ]
