# Generated by Django 2.1.3 on 2020-04-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_frontend_keep_source_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='imperva_api_id',
            field=models.TextField(default='', help_text='Imperva API ID'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='imperva_api_key',
            field=models.TextField(default='', help_text='Imperva API KEY'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='imperva_base_url',
            field=models.TextField(default='', help_text='Imperva Base URL'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='imperva_last_log_file',
            field=models.TextField(default='', help_text='Imperva Last Log File'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='imperva_private_key',
            field=models.TextField(default='', help_text='Imperva Private KEY'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='darwin_mode',
            field=models.TextField(choices=[('darwin', 'generate alerts'), ('both', 'enrich logs and generate alerts')],
                                   default='darwin',
                                   help_text="Ways to call Darwin: 'enrich' will wait for a score and add it to the data, 'alert' will simply pass the data for Darwin to process and will rely on its configured alerting methods"),
        ),
    ]
