# Generated by Django 2.1.3 on 2020-06-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20200519_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontendreputationcontext',
            name='dst_field',
            field=models.TextField(default='', help_text='Field name which will contains the searched value', verbose_name='Destination field name'),
        ),
        migrations.AlterField(
            model_name='frontendreputationcontext',
            name='arg_field',
            field=models.TextField(default='', help_text='Field name to predict with Rsyslog Database', verbose_name='Input field name'),
        ),
    ]
