# Generated by Django 2.1.3 on 2020-02-11 14:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_auto_20200602_1549'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetdataSettings',
        ),
        migrations.AlterField(
            model_name='frontendreputationcontext',
            name='reputation_ctx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.ReputationContext', verbose_name='IOC Database'),
        ),
    ]
