# Generated by Django 2.1.3 on 2020-09-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_auto_20200918_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='mdatp_api_appid',
            field=models.TextField(default='', help_text='Microsoft Defender ATP App ID', verbose_name='Microsoft Defender ATP App ID'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='mdatp_api_secret',
            field=models.TextField(default='', help_text='Microsoft Defender ATP App secret', verbose_name='Microsoft Defender ATP App secret'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='mdatp_api_tenant',
            field=models.TextField(default='', help_text='Microsoft Defender ATP Tenant ID', verbose_name='Microsoft Defender Tenant ID'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='mongodb_api_group_id',
            field=models.TextField(default='', help_text='MongoDB Group ID', verbose_name='MongoDB API group ID to retrieve log events from'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='mongodb_api_password',
            field=models.TextField(default='', help_text='MongoDB API password', verbose_name='MongoDB API password for authentication'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='mongodb_api_user',
            field=models.TextField(default='', help_text='MongoDB API user', verbose_name='MongoDB user for authentication'),
        )
    ]
