# Generated by Django 2.1.3 on 2020-11-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_auto_20200915_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='cortex_xdr_alerts_timestamp',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='frontend',
            name='cortex_xdr_apikey',
            field=models.TextField(default='', verbose_name='Cortex XDR API Key', help_text='API Key from Cortex XDR settings'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='cortex_xdr_apikey_id',
            field=models.TextField(default='', verbose_name='Cortex XDR API Key ID', help_text='ID of the API Key from Cortex XDR settings'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='cortex_xdr_host',
            field=models.TextField(default='xdr.domain.com', verbose_name='Cortex XDR FQDN', help_text='Cortex XDR api endpoint domain (without api-)'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='cortex_xdr_incidents_timestamp',
            field=models.DateTimeField(default=None),
        ),
    ]
