# Generated by Django 2.1.3 on 2021-02-04 00:03

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_auto_20210201_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='kafka_brokers',
            field=djongo.models.fields.ListField(default=['192.168.1.2:9092'], help_text='Kafka broker(s) to connect to', verbose_name='Kafka Broker(s)', null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='kafka_brokers',
            field=djongo.models.fields.ListField(default=['192.168.1.2:9092'], help_text='Kafka broker(s) to connect to', verbose_name='Kafka Broker(s)'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='kafka_consumer_group',
            field=models.TextField(default='my_group', help_text='Kafka consumer group to use to poll logs', verbose_name='Kafka consumer group'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='kafka_topic',
            field=models.TextField(default='mytopic', help_text='Kafka topic to connect to', verbose_name='Kafka Topic'),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='listening_mode',
            field=models.TextField(choices=[('udp', 'UDP'), ('tcp', 'TCP'), ('tcp,udp', 'TCP & UDP'), ('relp', 'RELP (TCP)'), ('file', 'FILE'), ('api', 'API CLIENT'), ('kafka', 'KAFKA')], default='tcp', help_text='TCP mode = HAProxy, UDP mode = Rsyslog'),
        ),
    ]
