# Generated by Django 2.1.3 on 2021-02-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_auto_20210204_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='proofpoint_tap_endpoint',
            field=models.TextField(choices=[('/all', 'all'), ('/clicks/blocked', 'clicks/blocked'), ('/clicks/permitted', 'clicks/permitted'), ('/messages/blocked', 'messages/blocked'), ('/messages/delivered', 'messages/delivered'), ('/issues', 'issues')], default='/all', help_text='ProofPoint TAP endpoint', verbose_name='Types of messages to query from Proofpoint API'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='proofpoint_tap_host',
            field=models.TextField(default='https://tap-api-v2.proofpoint.com', help_text='ProofPoint TAP host', verbose_name='ProofPoint API root url'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='proofpoint_tap_principal',
            field=models.TextField(default='', help_text='ProofPoint TAP principal', verbose_name="API 'principal' (username)"),
        ),
        migrations.AddField(
            model_name='frontend',
            name='proofpoint_tap_secret',
            field=models.TextField(default='', help_text='ProofPoint TAP secret', verbose_name="API 'secret' (password)"),
        ),
    ]
