# Generated by Django 2.1.3 on 2021-03-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_auto_20210217_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='redis_key',
            field=models.TextField(default='vulture', help_text='The redis key you want to pop from the queue / the redis channel you want to subscribe to', verbose_name='Redis key'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='redis_mode',
            field=models.TextField(choices=[('queue', 'Queue mode, using push/pop'), ('subscribe', 'Channel mode, using pub/sub')], default='queue', help_text="Redis comsumer mode - 'Queue' mode is recommended to avoid data loss", verbose_name='Redis consumer mode'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='redis_password',
            field=models.TextField(default='', help_text="Optional password to use via the 'AUTH' redis command when connecting to redis", verbose_name='Redis password'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='redis_port',
            field=models.PositiveIntegerField(default='6379', help_text='Default redis port is 6379', verbose_name='Redis port to use'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='redis_server',
            field=models.TextField(default='127.0.0.3', help_text='Default Vulture internal server is available on 127.0.0.3', verbose_name='Redis server to use'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='redis_use_lpop',
            field=models.BooleanField(default=False, help_text="Default queue mode uses 'RPOP', toggle the button if you want to use 'LPOP'", verbose_name='Use LPOP'),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='listening_mode',
            field=models.TextField(choices=[('udp', 'UDP'), ('tcp', 'TCP'), ('tcp,udp', 'TCP & UDP'), ('relp', 'RELP (TCP)'), ('file', 'FILE'), ('api', 'API CLIENT'), ('kafka', 'KAFKA'), ('redis', 'REDIS')], default='tcp', help_text='TCP mode = HAProxy, UDP mode = Rsyslog'),
        ),
    ]
