# Generated by Django 3.0.5 on 2021-03-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_auto_20210308_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='sentinel_one_apikey',
            field=models.TextField(default='', help_text='API key used to retrieve logs - as configured in SentinelOne settings', verbose_name='Sentinel One API key'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='sentinel_one_host',
            field=models.TextField(default='srv.sentinelone.net', help_text='Hostname (without scheme or path) of the SentinelOne server', verbose_name='SentinelOne Host'),
        ),
    ]
