# Generated by Django 3.0.5 on 2021-04-23 12:49

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_auto_20210414_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='kafka_options',
            field=djongo.models.fields.JSONField(default=[], help_text="Rsyslog imkafka 'confParams' options (See https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md)", verbose_name='Kafka client options'),
        ),
    ]
