# Generated by Django 3.0.5 on 2021-08-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0032_auto_20210423_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='rapid7_idr_apikey',
            field=models.TextField(default='', help_text='API key used to retrieve logs', verbose_name='Rapid7 IDR API key'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='rapid7_idr_host',
            field=models.TextField(default='eu.api.insight.rapid7.com', help_text='Hostname (without scheme or path) of the Rapid7 server', verbose_name='rapid7 IDR Host'),
        ),
    ]
