# Generated by Django 3.0.5 on 2021-09-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0033_auto_20210802_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='harfanglab_apikey',
            field=models.TextField(default='', help_text='API key to use to contact HarfangLab api', verbose_name='HarfangLab API key'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='harfanglab_host',
            field=models.TextField(default='', help_text='Hostname (without scheme or path) of the HarfangLab server', verbose_name='HarfangLab Host'),
        ),
    ]
