# Generated by Django 3.0.5 on 2021-11-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0034_auto_20210928_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='defender_client_id',
            field=models.TextField(default='', help_text="Client id of the OAuth endpoint to get an OAuth token before requesting Microsoft's APIs", verbose_name='Defender OAuth client id'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='defender_client_secret',
            field=models.TextField(default='', help_text="Client secret of the OAuth endpoint to get an OAuth token before requesting Microsoft's APIs", verbose_name='Defender OAuth client secret'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='defender_token_endpoint',
            field=models.TextField(default='', help_text="Complete enpoint address to get an Oauth token before requesting Microsoft's APIs", verbose_name='Defender token endpoint'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='vadesecure_host',
            field=models.TextField(default='', help_text='Hostname (without scheme or path) of the Vadesecure server', verbose_name='Vadesecure Host'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='vadesecure_login',
            field=models.TextField(default='', help_text='Login used to fetch the token for the Vadesecure API', verbose_name='Vadesecure login'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='vadesecure_password',
            field=models.TextField(default='', help_text='Password used to fetch the token for the Vadesecure API', verbose_name='Vadesecure password'),
        ),
    ]
