# Generated by Django 3.0.5 on 2021-12-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0035_auto_20211124_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='crowdstrike_client',
            field=models.TextField(default='', help_text="User's name", verbose_name='CrowdStrike Username'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='crowdstrike_client_id',
            field=models.TextField(default='', help_text='Client ID used for authentication', verbose_name='CrowdStrike Client ID'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='crowdstrike_client_secret',
            field=models.TextField(default='', help_text="Client's secret used for authentication", verbose_name="CrowdStrike Client's Secret"),
        ),
        migrations.AddField(
            model_name='frontend',
            name='crowdstrike_host',
            field=models.TextField(default='', help_text='Complete enpoint address', verbose_name='CrowdStrike Host'),
        ),
    ]
