# Generated by Django 3.0.5 on 2022-02-22 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0037_auto_20211208_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='vadesecure_o365_access_token',
            field=models.TextField(default='', verbose_name='API current cached token'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='vadesecure_o365_access_token_expiry',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AddField(
            model_name='frontend',
            name='vadesecure_o365_client_id',
            field=models.TextField(default='', help_text='Client ID used for authentication', verbose_name='Vadesecure O365 Client ID'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='vadesecure_o365_client_secret',
            field=models.TextField(default='', help_text="Client's secret used for authentication", verbose_name="Vadesecure O365 Client's Secret"),
        ),
        migrations.AddField(
            model_name='frontend',
            name='vadesecure_o365_host',
            field=models.TextField(default='', help_text='FQDN of the API endpoint', verbose_name='Vadesecure O365 Host'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='vadesecure_o365_tenant',
            field=models.TextField(default='', help_text='Tenant', verbose_name='Vadesecure O365 tenant'),
        ),
    ]
