# Generated by Django 3.0.5 on 2022-02-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0038_auto_20220222_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='nozomi_probe_host',
            field=models.TextField(default='', help_text='Hostname (without scheme or path) of the Nozomi Probe', verbose_name='Nozomi Probe Host'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='nozomi_probe_login',
            field=models.TextField(default='', help_text='User to use to contact Nozomi probe api', verbose_name='Nozomi Probe User'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='nozomi_probe_password',
            field=models.TextField(default='', help_text='Password to use to contact Nozomi probe api', verbose_name='Nozomi Probe Password'),
        )
    ]
