# Generated by Django 3.0.5 on 2022-03-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0039_auto_20220223_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='blackberry_cylance_app_id',
            field=models.TextField(default='', help_text='Client ID used for authentication', verbose_name='Blackberry Cylance Application ID'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='blackberry_cylance_app_secret',
            field=models.TextField(default='', help_text="Client's secret used for authentication", verbose_name="Blackberry Cylance Application's Secret"),
        ),
        migrations.AddField(
            model_name='frontend',
            name='blackberry_cylance_host',
            field=models.TextField(default='', help_text='FQDN of the API endpoint', verbose_name='Blackberry Cylance Host'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='blackberry_cylance_tenant',
            field=models.TextField(default='', help_text='Tenant', verbose_name='Blackberry Cylance tenant'),
        ),
    ]
