# Generated by Django 3.0.5 on 2022-04-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0040_auto_20220317_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='ms_sentinel_appid',
            field=models.TextField(default='', help_text='Microsoft Sentinel Client ID', verbose_name='Microsoft Sentinel App ID'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='ms_sentinel_appsecret',
            field=models.TextField(default='', help_text='Application Secret', verbose_name='Microsoft Sentinel App Secret'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='ms_sentinel_resource_group',
            field=models.TextField(default='', help_text='Resource Group name', verbose_name='Microsoft Sentinel Resource Group'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='ms_sentinel_subscription_id',
            field=models.TextField(default='', help_text='Subscription ID', verbose_name='Microsoft Sentinel Subscription ID'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='ms_sentinel_tenant_id',
            field=models.TextField(default='', help_text='Your Microsoft Tenant ID', verbose_name='Microsoft Sentinel Tenant ID'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='ms_sentinel_workspace',
            field=models.TextField(default='', help_text='Workspace name', verbose_name='Microsoft Sentinel Workspace'),
        )
    ]
