# Generated by Django 3.0.5 on 2022-06-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0041_auto_20220414_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='proofpoint_pod_cluster_id',
            field=models.TextField(default='', help_text='Cluster ID', verbose_name='Proofpoint PoD Cluster ID'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='proofpoint_pod_token',
            field=models.TextField(default='', help_text='Authentication token', verbose_name='Proofpoint PoD Authentication token'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='proofpoint_pod_uri',
            field=models.TextField(default='wss://logstream.proofpoint.com:443/v1/stream', help_text='Server URI', verbose_name='Proofpoint PoD URI'),
        ),
    ]
