# Generated by Django 3.0.5 on 2022-07-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0042_auto_20220616_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='waf_cloudflare_apikey',
            field=models.TextField(default='', help_text='WAF Cloudflare  API token', verbose_name='WAF Cloudflare API token'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='waf_cloudflare_zoneid',
            field=models.TextField(default='', help_text='WAF Cloudflare zone ID', verbose_name='WAF Cloudflare zone ID'),
        ),
    ]
