# Generated by Django 3.0.5 on 2022-07-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0043_auto_20220701_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='gsuite_alertcenter_admin_mail',
            field=models.TextField(default='', help_text='Google Alertcenter Admin email', verbose_name='Google Alertcenter Admin email for delegated wrights'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='gsuite_alertcenter_json_conf',
            field=models.TextField(default='', help_text='Your JSON Conf from Google', verbose_name='Google Alertcenter JSON Conf'),
        ),
    ]
