# Generated by Django 3.0.5 on 2022-07-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0044_auto_20220707_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='sophos_cloud_client_id',
            field=models.TextField(default='', help_text='Client ID', verbose_name='Sophos Cloud - Client ID'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='sophos_cloud_client_secret',
            field=models.TextField(default='', help_text='Client Secret', verbose_name='Sophos Cloud - Client Secret'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='sophos_cloud_tenant_id',
            field=models.TextField(default='', help_text='Tenant ID', verbose_name='Sophos Cloud - Tenant ID'),
        )
    ]
