# Generated by Django 3.0.5 on 2022-08-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0045_auto_20220713_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='trendmicro_worryfree_access_token',
            field=models.TextField(default='', help_text='Trendmicro Worryfree access token', verbose_name='Trendmicro Worryfree access token'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='trendmicro_worryfree_secret_key',
            field=models.TextField(default='', help_text='Trendmicro Worryfree secret key', verbose_name='Trendmicro Worryfree secret key'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='trendmicro_worryfree_server_name',
            field=models.TextField(default='cspi.trendmicro.com', help_text='Trendmicro Worryfree server name', verbose_name='Trendmicro Worryfree server name'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='trendmicro_worryfree_server_port',
            field=models.TextField(default='443', help_text='Trendmicro Worryfree server port', verbose_name='Trendmicro Worryfree server port'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='symantec_token',
            field=models.TextField(default='none', help_text='Symantec Token'),
        ),
    ]
