# Generated by Django 3.0.5 on 2022-09-13 16:43
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0047_auto_20220825_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='safenet_apikey',
            field=models.TextField(default='', help_text='Safenet Token API', verbose_name='Safenet API Key'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='safenet_tenant_code',
            field=models.TextField(default='', help_text='Your Safenet Tenant Code', verbose_name='Safenet Tenant Code'),
        ),
    ]