# Generated by Django 3.0.5 on 2023-02-01 00:31

from django.db import migrations, models
import djongo.models.fields

def set_default_waf_cloud_protector_timestamps(apps, schema_editor):
    frontend_model = apps.get_model("services", "Frontend")
    db_alias = schema_editor.connection.alias
    frontend_objects = frontend_model.objects.using(db_alias)

    for frontend in frontend_objects.all():
        frontend.waf_cloud_protector_timestamps = {'alert': {}, 'traffic': {}}
        frontend.save()
        print(f"Frontend '{frontend}' updated")


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0050_auto_20221219_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='waf_cloud_protector_api_key_priv',
            field=models.TextField(default='base64', help_text='base64 encodid private key to contact CloudProtector API', verbose_name='WAF CloudProtector private key'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='waf_cloud_protector_api_key_pub',
            field=models.TextField(default='base64', help_text='base64 encodid public key to contact CloudProtector API', verbose_name='WAF CloudProtector public key'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='waf_cloud_protector_host',
            field=models.TextField(default='api-region.cloudprotector.com', help_text='Hostname (without scheme or path) of the CloudProtector server', verbose_name='WAF CloudProtector host'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='waf_cloud_protector_provider',
            field=models.TextField(default='', help_text='Provider used to retrieve event from', verbose_name='WAF Cloud Protector provider'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='waf_cloud_protector_servers',
            field=models.TextField(default='www.example.com', help_text='Servers to for wich to retrieve traffic and alert events', verbose_name='WAF Cloud Protector servers'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='waf_cloud_protector_tenant',
            field=models.TextField(default='', help_text='Tenant used to retrieve event from', verbose_name='WAF Cloud Protector tenant'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='waf_cloud_protector_timestamps',
            field=djongo.models.fields.JSONField(default={'alert': {}, 'traffic': {}}),
        ),
        migrations.RunPython(set_default_waf_cloud_protector_timestamps, migrations.RunPython.noop),
    ]
