# Generated by Django 3.0.5 on 2023-02-16 14:00

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_auto_20230216_1400'),
        ('services', '0051_auto_20230201_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontend',
            name='cybereason_malops_timestamp',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='cybereason_malwares_timestamp',
        ),
    ]
