# Generated by Django 3.2.18 on 2023-05-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0053_auto_20230223_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='cisco_duo_host',
            field=models.TextField(default='api-XXXXXXXX.duosecurity.com', help_text='Cisco Duo API hostname', verbose_name='Cisco Duo API hostname'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='cisco_duo_ikey',
            field=models.TextField(default='DIWJ8X6AEYOR5OMC6TQ1', help_text='Cisco Duo API integration key', verbose_name='Cisco Duo API ikey'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='cisco_duo_offsets',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='frontend',
            name='cisco_duo_skey',
            field=models.TextField(default='Zh5eGmUq9zpfQnyUIu5OL9iWoMMv5ZNmk3zLJ4Ep', help_text='Cisco Duo API secret key', verbose_name='Cisco Duo API skey'),
        ),
    ]
