# Generated by Django 3.2.18 on 2023-05-24 13:40

from django.db import migrations, models
import djongo.models.fields

def add_default_cisco_duo_offsets(apps, schema_editor):
    frontend_model = apps.get_model("services", "frontend")
    db_alias = schema_editor.connection.alias
    frontends = frontend_model.objects.using(db_alias)

    for frontend in frontends:
        frontend.cisco_duo_offsets = dict()
        frontend.save()

class Migration(migrations.Migration):

    dependencies = [
        ('services', '0054_auto_20230524_1340'),
    ]

    operations = [

        migrations.AddField(
            model_name='frontend',
            name='cisco_duo_offsets',
            field=djongo.models.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='cisco_duo_ikey',
            field=models.TextField(default='', help_text='Cisco Duo API integration key', verbose_name='Cisco Duo API ikey'),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='cisco_duo_skey',
            field=models.TextField(default='', help_text='Cisco Duo API secret key', verbose_name='Cisco Duo API skey'),
        ),
        migrations.RunPython(add_default_cisco_duo_offsets, migrations.RunPython.noop),
    ]
