# Generated by Django 3.2.18 on 2023-05-24 13:40

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0054_auto_20230524_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontend',
            name='cisco_duo_ikey',
            field=models.TextField(default='', help_text='Cisco Duo API integration key', verbose_name='Cisco Duo API ikey'),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='cisco_duo_skey',
            field=models.TextField(default='', help_text='Cisco Duo API secret key', verbose_name='Cisco Duo API skey'),
        ),
    ]
