# Generated by Django 3.2.20 on 2023-08-10 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0057_auto_20230719_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='api_parser_custom_certificate',
            field=models.ForeignKey(help_text='Custom certificate to use.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_used_by_api_parser', to='system.x509certificate', verbose_name='Custom certificate'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='api_parser_verify_ssl',
            field=models.BooleanField(default=True, help_text='Verify SSL', verbose_name='Verify certificate'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='retarus_channel',
            field=models.TextField(default='', help_text='Retarus channel', verbose_name='Retarus channel'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='retarus_token',
            field=models.TextField(default='', help_text='Retarus token', verbose_name='Retarus token'),
        ),
    ]
