# Generated by Django 3.2.20 on 2023-09-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0058_auto_20230810_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontend',
            name='redis_server',
            field=models.TextField(default='127.0.0.5', help_text='Default Vulture internal master server is available on 127.0.0.5', verbose_name='Redis server to use'),
        ),
    ]
