# Generated by Django 3.2.21 on 2023-10-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0059_alter_frontend_redis_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='api_parser_custom_proxy',
            field=models.TextField(default='', help_text='Custom Proxy to use when requesting logs', verbose_name='Custom Proxy'),
        ),
    ]
