# Generated by Django 4.2.6 on 2023-10-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0060_auto_20231005_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='vectra_client_id',
            field=models.TextField(default='', help_text='Vectra client id', verbose_name='Vectra client id'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='vectra_host',
            field=models.TextField(default='', help_text='Vectra url', verbose_name='Vectra url'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='vectra_secret_key',
            field=models.TextField(default='', help_text='Vectra secret key', verbose_name='Vectra secret key'),
        ),
    ]
