# Generated by Django 4.2.6 on 2023-11-22 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0062_remove_frontend_timeout_connect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='custom_tl_frame_delimiter',
            field=models.IntegerField(default=-1, help_text='Additional frame delimiter', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(255)], verbose_name='Additional frame delimiter'),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='filebeat_module',
            field=models.TextField(choices=[('_custom', 'Custom Filebeat config'), ('activemq', 'Activemq'), ('apache', 'Apache'), ('auditd', 'Auditd'), ('aws', 'Aws'), ('awsfargate', 'Awsfargate'), ('azure', 'Azure'), ('barracuda', 'Barracuda'), ('bluecoat', 'Bluecoat'), ('cef', 'Cef'), ('checkpoint', 'Checkpoint'), ('cisco', 'Cisco'), ('coredns', 'Coredns'), ('crowdstrike', 'Crowdstrike'), ('cyberark', 'Cyberark'), ('cyberarkpas', 'Cyberarkpas'), ('cylance', 'Cylance'), ('elasticsearch', 'Elasticsearch'), ('envoyproxy', 'Envoyproxy'), ('f5', 'F5'), ('fortinet', 'Fortinet'), ('gcp', 'Gcp'), ('google_workspace', 'Google_workspace'), ('googlecloud', 'Googlecloud'), ('gsuite', 'Gsuite'), ('haproxy', 'Haproxy'), ('ibmmq', 'Ibmmq'), ('icinga', 'Icinga'), ('iis', 'Iis'), ('imperva', 'Imperva'), ('infoblox', 'Infoblox'), ('iptables', 'Iptables'), ('juniper', 'Juniper'), ('kafka', 'Kafka'), ('kibana', 'Kibana'), ('logstash', 'Logstash'), ('microsoft', 'Microsoft'), ('misp', 'Misp'), ('mongodb', 'Mongodb'), ('mssql', 'Mssql'), ('mysql', 'Mysql'), ('mysqlenterprise', 'Mysqlenterprise'), ('nats', 'Nats'), ('netflow', 'Netflow'), ('netscout', 'Netscout'), ('nginx', 'Nginx'), ('o365', 'O365'), ('okta', 'Okta'), ('oracle', 'Oracle'), ('osquery', 'Osquery'), ('panw', 'Panw'), ('pensando', 'Pensando'), ('postgresql', 'Postgresql'), ('proofpoint', 'Proofpoint'), ('rabbitmq', 'Rabbitmq'), ('radware', 'Radware'), ('redis', 'Redis'), ('santa', 'Santa'), ('snort', 'Snort'), ('snyk', 'Snyk'), ('sonicwall', 'Sonicwall'), ('sophos', 'Sophos'), ('squid', 'Squid'), ('suricata', 'Suricata'), ('system', 'System'), ('threatintel', 'Threatintel'), ('tomcat', 'Tomcat'), ('traefik', 'Traefik'), ('zeek', 'Zeek'), ('zookeeper', 'Zookeeper'), ('zoom', 'Zoom'), ('zscaler', 'Zscaler')], default='_custom', help_text='Filebeat built-in module'),
        ),
    ]
