# Generated by Django 4.2.7 on 2023-12-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0063_frontend_apex_api_key_frontend_apex_application_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='signalsciences_ngwaf_corp_name',
            field=models.TextField(default='', help_text='SignalSciences NGWAF corporation name', verbose_name='SignalSciences NGWAF corporation name'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='signalsciences_ngwaf_email',
            field=models.TextField(default='', help_text='SignalSciences NGWAF email', verbose_name='SignalSciences NGWAF email'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='signalsciences_ngwaf_site_name',
            field=models.TextField(default='', help_text='SignalSciences NGWAF site name', verbose_name='SignalSciences NGWAF site name'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='signalsciences_ngwaf_token',
            field=models.TextField(default='', help_text='SignalSciences NGWAF token', verbose_name='SignalSciences NGWAF token'),
        ),
    ]
