# Generated by Django 4.2.11 on 2024-03-06 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0066_frontend_redis_stream_acknowledge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontend',
            name='last_api_call',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='vadesecure_o365_access_token_expiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
