# Generated by Django 4.2.11 on 2024-03-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0067_alter_frontend_filebeat_module_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DarwinSettings',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='darwin_mode',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='darwin_policies',
        ),
    ]
