# Generated by Django 4.2.9 on 2024-07-04 13:15

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0070_frontend_last_collected_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='waf_barracuda_token',
            field=models.TextField(default='', help_text='Waf Barracuda token', verbose_name='Waf Barracuda token'),
        ),
    ]
