# Generated by Django 4.2.9 on 2024-08-20 15:48

from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields

def add_default_beyondtrust_pra_api_token(apps, schema_editor):
    frontend_model = apps.get_model("services", "frontend")
    db_alias = schema_editor.connection.alias
    frontends = frontend_model.objects.using(db_alias)

    for frontend in frontends:
        if not frontend.beyondtrust_pra_api_token:
            frontend.beyondtrust_pra_api_token = dict()
            frontend.save()

class Migration(migrations.Migration):

    dependencies = [
        ('services', '0072_frontend_crowdstrike_request_incidents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='beyondtrust_pra_api_token',
            field=djongo.models.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='frontend',
            name='beyondtrust_pra_client_id',
            field=models.TextField(default='', help_text='Beyondtrust PRA client id', verbose_name='Beyondtrust PRA client id'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='beyondtrust_pra_host',
            field=models.TextField(default='', help_text='Beyondtrust PRA host', verbose_name='Beyondtrust PRA host'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='beyondtrust_pra_secret',
            field=models.TextField(default='', help_text='Beyondtrust PRA secret', verbose_name='Beyondtrust PRA secret'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='reachfive_access_token',
            field=models.TextField(default='', help_text='ReachFive access token', verbose_name='ReachFive access token'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='reachfive_expire_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='ReachFive access token expire at', verbose_name='ReachFive access token expire at'),
        ),
        migrations.RunPython(add_default_beyondtrust_pra_api_token, migrations.RunPython.noop),
    ]
