# Generated by Django 4.2.9 on 2024-07-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0073_frontend_beyondtrust_pra_api_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='lockself_host',
            field=models.TextField(default='api.lockself.com', help_text='Lockself Host', verbose_name='Lockself Host'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='lockself_organization_id',
            field=models.TextField(default='', help_text='Lockself organization id', verbose_name='Lockself organization id'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='lockself_x_auth_token',
            field=models.TextField(default='', help_text='Lockself X-Auth-Token', verbose_name='Lockself X-Auth-Token'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='lockself_x_ls_token',
            field=models.TextField(default='', help_text='Lockself X-Ls-Token', verbose_name='Lockself X-Ls-Token'),
        ),
    ]
