# Generated by Django 4.2.11 on 2024-11-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0075_frontend_cisco_meraki_get_security_logs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='cortex_xdr_advanced_token',
            field=models.BooleanField(default=False, help_text='Enable advanced token'),
        ),
    ]
