# Generated by Django 4.2.18 on 2024-11-20 16:50

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0077_frontend_cisco_umbrella_managed_org_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='beyondtrust_reportings_api_token',
            field=djongo.models.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='frontend',
            name='beyondtrust_reportings_client_id',
            field=models.TextField(default='ex: 18xxxxxxxxxxxaf3e86b2xxxxxx77b4fc29eff', help_text='Beyondtrust Reportings client id', verbose_name='Beyondtrust Reportings client id'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='beyondtrust_reportings_get_access_session_logs',
            field=models.BooleanField(default=False, help_text='Retrieve Beyondtrust Reportings AccessSession logs', verbose_name='Retrieve Beyondtrust Reportings AccessSession logs'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='beyondtrust_reportings_get_support_session_logs',
            field=models.BooleanField(default=False, help_text='Retrieve Beyondtrust Reportings SupportSession logs', verbose_name='Retrieve Beyondtrust Reportings SupportSession logs'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='beyondtrust_reportings_get_team_logs',
            field=models.BooleanField(default=False, help_text='Retrieve Beyondtrust Reportings Team logs', verbose_name='Retrieve Beyondtrust Reportings Team logs'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='beyondtrust_reportings_get_vault_account_activity_logs',
            field=models.BooleanField(default=False, help_text='Retrieve Beyondtrust Reportings VaultAccountActivity logs', verbose_name='Retrieve Beyondtrust Reportings VaultAccountActivity logs'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='beyondtrust_reportings_host',
            field=models.TextField(default='ex: https://xxx.xxx.com', help_text='Beyondtrust Reportings host', verbose_name='Beyondtrust Reportings host'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='beyondtrust_reportings_secret',
            field=models.TextField(default='ex: Oxxxxxxxxxxqep8xxxxxxx22Y8S98GPcHkgNMK', help_text='Beyondtrust Reportings secret', verbose_name='Beyondtrust Reportings secret'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='catonetworks_account_id',
            field=models.TextField(default='', help_text='Catonetworks account id', verbose_name='Catonetworks account id'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='catonetworks_api_key',
            field=models.TextField(default='', help_text='Catonetworks API Key', verbose_name='Catonetworks API Key'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='catonetworks_marker',
            field=models.TextField(default='', help_text='Catonetworks marker', verbose_name='Catonetworks marker'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='infoblox_threat_defense_host',
            field=models.TextField(default='https://XXX.infoblox.com', help_text='Infoblox Threat Defense Host', verbose_name='Infoblox Threat Defense Host'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='infoblox_threat_defense_token',
            field=models.TextField(default='', help_text='Infoblox Threat Defense Token', verbose_name='Infoblox Threat Defense Token'),
        ),
    ]
