# Generated by Django 4.2.18 on 2025-02-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0078_frontend_beyondtrust_reportings_api_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='netskope_get_application_logs',
            field=models.BooleanField(default=True, help_text='Retrieve Netskope application logs', verbose_name='Retrieve Netskope application logs'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='netskope_get_network_logs',
            field=models.BooleanField(default=True, help_text='Retrieve Netskope network logs', verbose_name='Retrieve Netskope network logs'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='netskope_get_page_logs',
            field=models.BooleanField(default=True, help_text='Retrieve Netskope page logs', verbose_name='Retrieve Netskope page logs'),
        ),
    ]
