# Generated by Django 4.2.18 on 2025-03-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0079_frontend_netskope_get_application_logs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='varonis_api_key',
            field=models.TextField(default='', help_text='Varonis API Key', verbose_name='Varonis API Key'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='varonis_host',
            field=models.TextField(default='', help_text='Varonis Host', verbose_name='Varonis Host'),
        ),
    ]
