# Generated by Django 4.2.20 on 2025-04-07 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0081_frontend_armis_centrix_get_activity_logs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='extrahop_access_token',
            field=models.TextField(default='', help_text='Extrahop access token', verbose_name='Extrahop access token'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='extrahop_expire_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Extrahop token expiration date', verbose_name='Extrahop token expiration date'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='extrahop_host',
            field=models.TextField(default='', help_text='Extrahop host', verbose_name='Extrahop host'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='extrahop_id',
            field=models.TextField(default='', help_text='Extrahop id', verbose_name='Extrahop id'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='extrahop_secret',
            field=models.TextField(default='', help_text='Extrahop secret', verbose_name='Extrahop secret'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='perception_point_x_ray_host',
            field=models.TextField(default='', help_text='Perception Point X Ray host', verbose_name='Perception Point X Ray host'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='perception_point_x_ray_token',
            field=models.TextField(default='', help_text='Perception Point X Ray API Key', verbose_name='Perception Point X Ray API Key'),
        ),
    ]
