# Generated by Django 4.2.20 on 2025-04-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0082_frontend_extrahop_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='healthcheck_service',
            field=models.BooleanField(default=False, help_text="Don't accept sessions if service is not ready", verbose_name='Healthckeck service'),
        ),
    ]
