# Generated by Django 4.2.21 on 2025-05-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0083_frontend_healthcheck_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='cisco_meraki_get_configuration_changes_logs',
            field=models.BooleanField(default=False, help_text='Get configuration changes logs', verbose_name='Get configuration changes logs'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='hornetsecurity_app_id',
            field=models.TextField(default='', help_text="Hornetsecurity header's APP-ID", verbose_name="Hornetsecurity header's APP-ID"),
        ),
        migrations.AddField(
            model_name='frontend',
            name='hornetsecurity_token',
            field=models.TextField(default='', help_text='Hornetsecurity access token', verbose_name='Hornetsecurity access token'),
        ),
    ]
