# Generated by Django 4.2.21 on 2025-06-23 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0085_frontend_checkpoint_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='sentinel_one_identity_graph_console_url',
            field=models.TextField(default='', help_text='Sentinel One Identity Graph Console URL', verbose_name='Sentinel One Identity Graph Console URL'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='sentinel_one_identity_graph_token',
            field=models.TextField(default='', help_text='Sentinel One Identity Graph Token', verbose_name='Sentinel One Identity Graph Token'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='ubika_access_expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Ubika refresh token expiration timestamp', verbose_name='Ubika refresh token expiration timestamp'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='ubika_access_token',
            field=models.TextField(default='', help_text='Ubika access token', verbose_name='Ubika access token'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='ubika_base_refresh_token',
            field=models.TextField(default='', help_text='Ubika base refresh token (used to establish first login)', verbose_name='Ubika base refresh token (used to establish first login)'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='ubika_namespaces',
            field=models.JSONField(default=[], help_text='Ubika namespaces to fetch', verbose_name='Ubika namespaces to fetch'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='ubika_refresh_token',
            field=models.TextField(default='', help_text='Ubika refresh token', verbose_name='Ubika refresh token'),
        ),
    ]
