# Generated by Django 4.2.24 on 2025-09-12 08:53

from django.db import migrations, models

def add_missing_default_custom_actions(apps, schema_editor):
    frontend_model = apps.get_model("services", "frontend")
    db_alias = schema_editor.connection.alias
    frontends = frontend_model.objects.using(db_alias)

    for frontend in frontends:
        frontend.custom_actions = list()
        frontend.save()


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0088_rename_sentinel_one_identity_graph_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='custom_actions',
            field=models.JSONField(blank=True, default=[], help_text='Rsyslog custom operations inserted in the ruleset.', null=True, verbose_name='Rsyslog custom operations'),
        ),
        migrations.RunPython(add_missing_default_custom_actions, migrations.RunPython.noop),
    ]
