# Generated by Django 4.2.24 on 2025-09-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0089_frontend_custom_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='messagetrace_o365_client_id',
            field=models.TextField(default='', help_text='MessageTrace O365 Client ID'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='messagetrace_o365_client_secret',
            field=models.TextField(default='', help_text='MessageTrace O365 Client Secret'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='messagetrace_o365_serialized_token',
            field=models.TextField(default='', help_text='MessageTrace O365 Serialized Token'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='messagetrace_o365_tenant_id',
            field=models.TextField(default='', help_text='MessageTrace O365 Tenant ID'),
        ),
    ]
