# Generated by Django 4.2.24 on 2025-10-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0090_frontend_messagetrace_o365_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontend',
            name='filebeat_listening_mode',
            field=models.TextField(choices=[('tcp', 'TCP'), ('udp', 'UDP'), ('file', 'File'), ('aws-cloudwatch', 'AWS Cloudwatch'), ('aws-s3', 'AWS S3'), ('azure-eventhub', 'Azure Event hub'), ('azure-blob-storage', 'Azure Blob Storage'), ('benchmark', 'Benchmark'), ('cel', 'CEL'), ('cloudfoundry', 'Cloud Foundry'), ('cometd', 'CometD'), ('entity-analytics', 'Entity Analytics'), ('filestream', 'Filestream'), ('gcp-pubsub', 'GCP Pub/Sub'), ('gcs', 'Google Cloud Storage'), ('http_endpoint', 'HTTP Endpoint'), ('httpjson', 'HTTP JSON'), ('mqtt', 'MQTT'), ('netflow', 'NetFlow'), ('salesforce', 'Salesforce'), ('streaming', 'Streaming')], default='tcp', help_text='TCP mode = HAProxy, UDP mode = Filebeat'),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='filebeat_module',
            field=models.TextField(choices=[('_custom', 'Custom Filebeat config'), ('activemq', 'Activemq'), ('apache', 'Apache'), ('auditd', 'Auditd'), ('aws', 'Aws'), ('awsfargate', 'Awsfargate'), ('azure', 'Azure'), ('cef', 'Cef'), ('checkpoint', 'Checkpoint'), ('cisco', 'Cisco'), ('coredns', 'Coredns'), ('crowdstrike', 'Crowdstrike'), ('cyberarkpas', 'Cyberarkpas'), ('elasticsearch', 'Elasticsearch'), ('envoyproxy', 'Envoyproxy'), ('fortinet', 'Fortinet'), ('gcp', 'Gcp'), ('google_workspace', 'Google_workspace'), ('haproxy', 'Haproxy'), ('ibmmq', 'Ibmmq'), ('icinga', 'Icinga'), ('iis', 'Iis'), ('iptables', 'Iptables'), ('juniper', 'Juniper'), ('kafka', 'Kafka'), ('kibana', 'Kibana'), ('logstash', 'Logstash'), ('microsoft', 'Microsoft'), ('misp', 'Misp'), ('mongodb', 'Mongodb'), ('mssql', 'Mssql'), ('mysql', 'Mysql'), ('mysqlenterprise', 'Mysqlenterprise'), ('nats', 'Nats'), ('netflow', 'Netflow'), ('nginx', 'Nginx'), ('o365', 'O365'), ('okta', 'Okta'), ('oracle', 'Oracle'), ('osquery', 'Osquery'), ('panw', 'Panw'), ('pensando', 'Pensando'), ('postgresql', 'Postgresql'), ('rabbitmq', 'Rabbitmq'), ('redis', 'Redis'), ('salesforce', 'Salesforce'), ('santa', 'Santa'), ('snyk', 'Snyk'), ('sophos', 'Sophos'), ('suricata', 'Suricata'), ('system', 'System'), ('threatintel', 'Threatintel'), ('traefik', 'Traefik'), ('zeek', 'Zeek'), ('zookeeper', 'Zookeeper'), ('zoom', 'Zoom')], default='_custom', help_text='Filebeat built-in module'),
        ),
    ]
