# Generated by Django 4.2.24 on 2025-10-20 14:13

from django.db import migrations, models


def add_missing_perception_point_x_ray_case_types(apps, schema_editor):
    frontend_model = apps.get_model("services", "frontend")
    db_alias = schema_editor.connection.alias
    frontends = frontend_model.objects.using(db_alias)

    for frontend in frontends:
        frontend.perception_point_x_ray_case_types = list()
        frontend.save()


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0091_alter_frontend_filebeat_listening_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='perception_point_x_ray_case_types',
            field=models.JSONField(default=[], help_text='Perception Point X Ray Case Types', verbose_name='Perception Point X Ray Case Types'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='perception_point_x_ray_environment_id',
            field=models.PositiveIntegerField(default=0, help_text='Perception Point X Ray Environment ID', verbose_name='Perception Point X Ray Environment ID'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='perception_point_x_ray_organization_id',
            field=models.PositiveIntegerField(default=0, help_text='Perception Point X Ray Organization ID', verbose_name='Perception Point X Ray Organization ID'),
        ),
        migrations.RunPython(add_missing_perception_point_x_ray_case_types, migrations.RunPython.noop),
    ]
