# Generated by Django 4.2.24 on 2025-11-04 16:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0028_alter_tlsprofile_ca_cert_and_more'),
        ('services', '0092_frontend_perception_point_x_ray_case_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='cnapp_wiz_access_expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Cnapp Wiz refresh token expiration timestamp', verbose_name='Cnapp Wiz refresh token expiration timestamp'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='cnapp_wiz_access_token',
            field=models.TextField(default='', help_text='Cnapp Wiz access token', verbose_name='Cnapp Wiz access token'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='cnapp_wiz_api_url',
            field=models.TextField(default='https://api.eu15.app.wiz.io/graphql', help_text='Cnapp Wiz API URL', verbose_name='Cnapp Wiz API URL'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='cnapp_wiz_client_id',
            field=models.TextField(default='', help_text='Cnapp Wiz Client ID'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='cnapp_wiz_client_secret',
            field=models.TextField(default='', help_text='Cnapp Wiz Client Secret'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='tls_profile',
            field=models.ForeignKey(blank=True, default=None, help_text='TLSProfile object to use.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='redis_frontends', to='system.tlsprofile', verbose_name='Redis TLS Profile to use'),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='api_parser_use_proxy',
            field=models.BooleanField(default=False, help_text='Use a proxy to connect to distant endpoint', verbose_name='Use Proxy'),
        ),
    ]
