# Generated by Django 2.1.3 on 2019-08-29 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('workflow', '0003_auto_20190829_1041')
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessControl',
        ),
    ]
