# Generated by Django 3.0.5 on 2021-03-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210126_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='openidrepository',
            name='scopes',
            field=models.JSONField(default=['openid'], help_text='Scope to send while requesting token', verbose_name='Token scope'),
        ),
    ]
