# Generated by Django 3.0.5 on 2021-03-17 10:41

from django.db import migrations, models
from toolkit.postgresql.postgres_base import PostgresBase


def update_repo_attributes(apps, schema_editor):
    """
    Update repo_attributes structure in authentication_userauthentication table
    Migration function from MongoDB to PostgreSQL
    """
    p = PostgresBase()
    p.connect_primary()
    
    # If the node is not yet installed, no need to process
    if not p.conn:
        return

    try:
        # Check if the database and table exist
        if not p.database_exists('vulture'):
            print("Database 'vulture' does not exist, skipping repo_attributes update")
            return

        if not p.table_exists('authentication_userauthentication', schema='public'):
            print("Table 'authentication_userauthentication' does not exist, skipping repo_attributes update")
            return

        with p.conn.cursor() as cursor:
            # Set the search path to the vulture schema
            cursor.execute("SET search_path TO vulture, public")
            
            # Fetch all portal records
            cursor.execute("""
                SELECT id, name, repo_attributes
                FROM authentication_userauthentication
                WHERE repo_attributes IS NOT NULL
            """)

            portals = cursor.fetchall()

            for portal in portals:
                portal_id = portal['id']
                portal_name = portal['name']
                existing_repo_attributes = portal['repo_attributes']

                # Parse repo_attributes if it's stored as JSON/JSONB
                if isinstance(existing_repo_attributes, str):
                    import json
                    try:
                        existing_repo_attributes = json.loads(existing_repo_attributes)
                    except json.JSONDecodeError:
                        print(f"Could not parse repo_attributes for portal {portal_name}, skipping")
                        continue

                # Transform the repo_attributes structure
                new_repo_attributes = []
                if existing_repo_attributes and isinstance(existing_repo_attributes, list):
                    for r in existing_repo_attributes:
                        if isinstance(r, dict) and 'key' in r and 'source_attr' in r:
                            new_repo_attributes.append({
                                'condition_var_kind': "constant",
                                'condition_var_name': "1",
                                'condition_criterion': "equals",
                                'condition_match': "1",
                                'action_var_name': r['key'],
                                'action_var_kind': r['source_attr'],
                                'action_var': r['key']
                            })

                # Update the record with new structure
                if new_repo_attributes:
                    # Convert to JSON for storage in JSONB column
                    import json
                    new_repo_attributes_json = json.dumps(new_repo_attributes)

                    cursor.execute("""
                        UPDATE authentication_userauthentication
                        SET repo_attributes = %s::jsonb
                        WHERE id = %s
                    """, (new_repo_attributes_json, portal_id))

                    print(f"Portal {portal_name} updated")
                else:
                    print(f"Portal {portal_name} has no valid repo_attributes to update")

            # Commit the changes
            p.conn.commit()
            print(f"Successfully updated repo_attributes for {len(portals)} portals")

    except Exception as e:
        if p.conn:
            p.conn.rollback()
        print(f"Error updating repo_attributes: {e}")
        # Depending on your migration strategy, you might want to raise or log this
        import logging
        logger = logging.getLogger('system')
        logger.error(f"Failed to update repo_attributes: {e}", exc_info=1)


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20210317_1013'),
    ]

    operations = [
        migrations.RunPython(update_repo_attributes, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='repoattributes',
            name='key',
        ),
        migrations.RemoveField(
            model_name='repoattributes',
            name='source_attr',
        ),
        migrations.AddField(
            model_name='repoattributes',
            name='action_var',
            field=models.TextField(default='true'),
        ),
        migrations.AddField(
            model_name='repoattributes',
            name='action_var_kind',
            field=models.TextField(choices=[('constant', 'Constant value'), ('claim', 'Claim attribute'), ('repo', 'Repository attribute'), ('merge', 'Merge attribute as list'), ('claim_pref', 'Use claim, or repo attr if not present'), ('repo_pref', 'Use repo attr, or claim if not present')], default='constant'),
        ),
        migrations.AddField(
            model_name='repoattributes',
            name='action_var_name',
            field=models.TextField(default='admin'),
        ),
        migrations.AddField(
            model_name='repoattributes',
            name='condition_criterion',
            field=models.TextField(choices=[('equals', 'equals to'), ('exists', 'exists'), ('not exists', 'does not exists'), ('contains', 'contains'), ('not contains', 'does not contains'), ('startswith', 'starts with'), ('endswith', 'ends with')], default='equals'),
        ),
        migrations.AddField(
            model_name='repoattributes',
            name='condition_match',
            field=models.TextField(default='test@abcd.fr'),
        ),
        migrations.AddField(
            model_name='repoattributes',
            name='condition_var_kind',
            field=models.TextField(choices=[('claim', 'Claim attribute'), ('repo', 'Repository attribute'), ('constant', 'Constant')], default='claim'),
        ),
        migrations.AddField(
            model_name='repoattributes',
            name='condition_var_name',
            field=models.TextField(default='email'),
        ),
        migrations.AlterField(
            model_name='portaltemplate',
            name='html_error',
            field=models.TextField(
                default='<!DOCTYPE html>\n<html>\n <head>\n    <meta charset="utf-8" />\n    <title>Vulture Error</title>\n    <link rel="stylesheet" href="/templates/static/html/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">\n    <style>\n        {{style}}\n    </style>\n </head>\n <body>\n    <div class="container">\n        <div class="card card-container">\n            <img id="vulture_img" src="{{image_1}}"/>\n            <p>{{message}}</p>\n        </div>\n    </div>\n </body>\n</html>',
                help_text='HTML General content for error pages'),
        ),
        migrations.AlterField(
            model_name='portaltemplate',
            name='html_login',
            field=models.TextField(
                default='<!DOCTYPE html>\n<html>\n<head>\n    <meta charset="utf-8"/>\n    <title>Vulture Login</title>\n    <link rel="stylesheet" href="/templates/static/html/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">\n    <style>{{style}}</style>\n </head>\n <body>\n    <div class="container">\n        <div class="card card-container">\n            <form action=\'\' method=\'POST\' autocomplete=\'off\' class=\'form-signin\'>\n                <img id="vulture_img" src="{{image_1}}"/>\n                {% if error_message != "" %}\n                  <div class="alert alert-danger" role="alert">{{error_message}}</div>\n                {% endif %}\n                <span id="reauth-email" class="reauth-email"></span>\n                <input type="text" name="{{input_login}}" class="form-control" placeholder="Login" required/>\n                <input type="password" name="{{input_password}}" class="form-control" placeholder="Password" required/>\n                {% if captcha %}\n                    {{captcha}}\n                    <input type="text" name="{{input_captcha}}" class="form-control" placeholder="Captcha" required/>\n\n                {% endif %}\n                <button class="btn btn-lg btn-warning btn-block btn-signin" type="submit">{{login_submit_field}}</button>\n                {% for repo in openid_repos %}\n                <a href="{{repo.start_url}}">Login with {{repo.provider}}</a>\n                {% endfor %}\n                <a href="{{lostPassword}}">Forgotten password ?</a>\n            </form>\n        </div>\n    </div>\n </body>\n</html>',
                help_text='HTML Content for the login page'),
        ),
        migrations.AlterField(
            model_name='portaltemplate',
            name='html_message',
            field=models.TextField(
                default='<!DOCTYPE html>\n<html>\n <head>\n    <meta charset="utf-8" />\n    <title>Vulture Info</title>\n    <link rel="stylesheet" href="/templates/static/html/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">\n    {{style}}\n </head>\n <body>\n    <div class="container">\n        <div class="card card-container">\n            <img id="vulture_img" src="{{image_1}}"/>\n            <p>{{message}}</p>\n            {% if link_redirect %}<a href="{{link_redirect}}">Go back</a>{% endif %}\n        </div>\n    </div>\n </body>\n</html>',
                help_text='HTML Content for the message page'),
        ),
        migrations.AlterField(
            model_name='portaltemplate',
            name='html_password',
            field=models.TextField(
                default='<!DOCTYPE html>\n<html>\n <head>\n    <meta charset="utf-8" />\n    <title>Vulture Change Password</title>\n    <link rel="stylesheet" href="..//templates/static/html/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">\n    {{style}}\n </head>\n <body>\n    <div class="container">\n        <div class="card card-container" style="text-align:center;">\n            {{form_begin}}\n                <img id="vulture_img" src="{{image_1}}"/>\n                {% if error_message %}\n                    <div class="alert alert-danger">{{error_message}}</div>\n                {% endif %}\n                {% if dialog_change %}\n                    <p>Please fill the form to change your current password :</p>\n                    {{input_password_old}}\n                    {{input_password_1}}\n                    {{input_password_2}}\n                    {{input_submit}}\n\n                {% elif dialog_lost %}\n                    <p>Please enter an email address to reset your password:</p>\n\n                    {{input_email}}\n                    {{input_submit}}\n\n                {% endif %}\n            {{form_end}}\n        </div>\n    </div>\n </body>\n</html>\n',
                help_text='HTML Content for the password change page'),
        ),
        migrations.AlterField(
            model_name='portaltemplate',
            name='html_registration',
            field=models.TextField(
                default='<!DOCTYPE html>\n<html>\n <head>\n    <meta charset="utf-8" />\n    <title>Titre</title>\n    <link rel="stylesheet" href="/templates/static/html/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">\n    {{style}}\n </head>\n <body>\n    <div class="container">\n        <div class="card card-container" style="text-align:center;">\n            {{form_begin}}\n                <img id="vulture_img" src="{{image_1}}"/>\n                {% if error_message %}\n                    <div class="alert alert-danger">{{error_message}}</div>\n                {% endif %}\n                {{captcha}}\n                {{input_captcha}}\n                {% if step2 %}\n                    <p>Please fill the form to register your account :</p>\n                    {{input_username}}\n                    {% if ask_phone %}\n                    {{input_phone}}\n                    {% endif %}\n                    {{input_password_1}}\n                    {{input_password_2}}\n                    {{input_submit}}\n\n                {% elif step1 %}\n                    <p>Please enter your email address to receive the registration mail :</p>\n                    {{input_email}}\n                    {{input_submit}}\n                {% endif %}\n            {{form_end}}\n        </div>\n    </div>\n </body>\n</html>',
                help_text='HTML Content for registration pages'),
        ),
        migrations.AlterField(
            model_name='portaltemplate',
            name='html_self',
            field=models.TextField(
                default='<!DOCTYPE html>\n<html>\n <head>\n    <meta charset="utf-8" />\n    <title>Vulture Self-Service</title>\n    <link rel="stylesheet" href="/templates/static/html/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">\n    {{style}}\n </head>\n <body>\n    <div class="container">\n        <div class="card card-container" style="text-align:center;" id="self_service">\n            <img id="vulture_img" src="{{image_1}}"/>\n            <br><br>\n            {% if error_message != "" %}\n                <div class="alert alert-danger">{{error_message}}</div>\n            {% endif %}\n            <p>Hello <b>{{username}}</b>!</p>\n            <p>You currently have access to the following apps:</p>\n            <ul class="list-group">\n                {% for app in application_list %}\n                  <li class="list-group-item"><b>{{app.name}}</b> - <a href="{{app.url}}">{{app.url}}</a>{% if app.status %}<span class="badge">Logged</span>{% endif %}</li>\n                {% endfor %}\n            </ul>\n            <a href="{{changePassword}}">Change password</a>\n            <br><a href="{{logout}}">Logout</a>\n        </div>\n    </div>\n </body>\n</html>',
                help_text='HTML Content for the self-service page'),
        )
    ]
