# Generated by Django 3.0.5 on 2021-04-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20210317_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthentication',
            name='disconnect_url',
            field=models.TextField(default='^{{workflow.public_dir}}/logout\\?userid=[^&]+', help_text="Regex for the application disconnect page (ex: 'logout\\?sessid=.*'", verbose_name='Disconnect regex'),
        ),
    ]
