# Generated by Django 3.0.5 on 2021-04-23 09:40

import authentication.user_portal.models
import bson.objectid
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20210423_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprepository',
            name='totp_label',
            field=models.TextField(default='Vulture App', help_text='Label to show in phone application', verbose_name='Time-based OTP label'),
        ),
        migrations.CreateModel(
            name='TOTPProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TextField(default='', verbose_name="User's login")),
                ('encrypted_value', models.TextField(default='')),
                ('auth_repository', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authentication.BaseRepository', verbose_name='Authentication repository')),
                ('totp_repository', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='totp_profiles_of', to='authentication.OTPRepository', verbose_name='TOTP authentication repository')),
            ],
        ),
    ]
