# Generated by Django 3.0.5 on 2021-05-04 22:33

import authentication.user_portal.models
import bson.objectid
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20210423_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='repoattributes',
            name='assignator',
            field=models.TextField(choices=[('=', 'set'), ('+=', 'append')], default='='),
        ),
        migrations.AlterField(
            model_name='userauthentication',
            name='repo_attributes',
            field=djongo.models.fields.ArrayField(default=None, help_text='Repo attributes whitelist, for re-use in SSO and ACLs', model_container=authentication.user_portal.models.RepoAttributes, model_form_class=authentication.user_portal.models.RepoAttributesForm, null=True, verbose_name='Create user scope'),
        )
    ]
