# Generated by Django 3.0.5 on 2021-07-09 05:27

import bson.objectid
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0032_auto_20210423_1539'),
        ('authentication', '0012_auto_20210615_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthentication',
            name='external_fqdn',
            field=models.TextField(default='auth.testing.tr', help_text='Listening FQDN for external portal', verbose_name='FQDN'),
        ),
    ]
