# Generated by Django 3.0.5 on 2021-08-12 20:07

import bson.objectid
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields

# Ensure PortalTemplate objects have unique names before enforcing unicity
def save_user_scope(apps, schema_editor):
    portal_template_model = apps.get_model("authentication", "PortalTemplate")
    db_alias = schema_editor.connection.alias
    portal_template_objects = portal_template_model.objects.using(db_alias)

    # Search for objects with equivalent names
    duplicate_names = []
    for portal_template in portal_template_objects.all():
        if portal_template_objects.filter(name=portal_template.name).count() > 1:
            duplicate_names.append(portal_template.name)

    # For each name with duplicates, cycle through them to add a suffix to their name
    for duplicate_name in duplicate_names:
        print(f"renaming portals with name {duplicate_name}")
        i = 1
        for template in portal_template_objects.filter(name=duplicate_name):
            template.name = template.name + f"_{i}"
            i = i + 1
            template.save()


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0033_auto_20210802_1427'),
        ('authentication', '0013_auto_20210709_0527'),
    ]

    operations = [
        migrations.RunPython(save_user_scope, migrations.RunPython.noop),

        migrations.AlterField(
            model_name='portaltemplate',
            name='email_body',
            field=models.TextField(default='<html>\n<head>\n</head>\n<body>\n<p>Dear Sir/Madam <b>{{username}}</b>, <br><br>\n\nWe got a request to reset your account on {{ app.url }}.<br><br>\n\nClick here to reset your password: <a href="{{resetLink}}">Reset password</a><br><br>\n\nIf you ignore this message, your password won\'t be changed.<br>\nIf you didn\'t request a password reset, <a href="mailto:abuse@vulture">let us know</a><br>\n</body>\n</html>', help_text='Email content for password reset'),
        ),
        migrations.AlterField(
            model_name='portaltemplate',
            name='email_register_body',
            field=models.TextField(default='<html>\n    <head>\n        <title>Vulture registration</title>\n    </head>\n    <body>\n        <p>Dear Sir/Madam <b>{{username}}</b>, <br><br>\n\n        We got a request to register your account on {{ app.url }}.<br><br>\n\n        Click here to validate the registration : <a href="{{registerLink}}">Register account</a><br><br>\n\n        If you ignore this message, your account won\'t be confirmed.<br>\n        If you didn\'t request a registration, <a href="mailto:abuse@vulture">let us know</a><br>\n    </body>\n</html>', help_text='Email sender for registration'),
        ),
        migrations.AlterField(
            model_name='portaltemplate',
            name='html_login',
            field=models.TextField(default='<!DOCTYPE html>\n<html>\n<head>\n    <meta charset="utf-8"/>\n    <title>Vulture Login</title>\n    <link rel="stylesheet" href="/templates/static/html/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">\n    <style>{{style}}</style>\n </head>\n <body>\n    <div class="container">\n        <div class="card card-container">\n            <form action=\'\' method=\'POST\' autocomplete=\'off\' class=\'form-signin\'>\n                <img id="vulture_img" src="{{image_1}}"/>\n                {% if error_message != "" %}\n                  <div class="alert alert-danger" role="alert">{{error_message}}</div>\n                {% endif %}\n                <span id="reauth-email" class="reauth-email"></span>\n                <input type="text" name="{{input_login}}" class="form-control" placeholder="Login" required/>\n                <input type="password" name="{{input_password}}" class="form-control" placeholder="Password" required/>\n                {% if captcha %}\n                    {{captcha}}\n                    <input type="text" name="{{input_captcha}}" class="form-control" placeholder="Captcha" required/>\n\n                {% endif %}\n                <button class="btn btn-lg btn-warning btn-block btn-signin" type="submit">{{login_submit_field}}</button>\n                {% for repo in openid_repos %}\n                <a href="{{repo.start_url}}">Login with {{repo.name}} ({{repo.provider}})</a><br>\n                {% endfor %}\n                <a href="{{lostPassword}}">Forgotten password ?</a>\n            </form>\n        </div>\n    </div>\n </body>\n</html>', help_text='HTML Content for the login page'),
        ),
        migrations.AlterField(
            model_name='portaltemplate',
            name='html_otp',
            field=models.TextField(default='<!DOCTYPE html>\n<html>\n <head>\n    <meta charset="utf-8" />\n    <title>Vulture OTP Authentication</title>\n    <link rel="stylesheet" href="/templates/static/html/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">\n    <style>{{style}}</style>\n </head>\n <body> \n    <div class="container">\n        <div class="card card-container" style="text-align:center;">\n            {% if error_message != "" %}\n                  <div class="alert alert-danger" role="alert">{{error_message}}</div>\n            {% endif %}\n            <p>OTP Form</p>\n            <form class="form-signin" autocomplete="off" action="" method="POST">\n                {% if onetouch %}\n                  {{otp_onetouch_field}}\n                {% else %}\n                <input type="text" name="vltprtlkey" class="form-control" placeholder="Key" required/>\n                <button class="btn btn-lg btn-warning btn-block btn-signin" type="submit">{{otp_submit_field}}</button>\n                {% endif %}\n            </form>\n            <form class="form-signin" autocomplete="off" action="" method="POST">\n                {% if resend_button %}\n                    <button class="btn btn-lg btn-warning btn-block btn-signin" name="{{input_otp_resend}}" value="yes">{{otp_resend_field}} {{otp_type}}</button>\n                {% endif %}\n                {% if qrcode %}\n                    <p>Register the following QRcode on your phone :\n                    <img src="{{qrcode}}" alt="Failed to display QRcode" height="270" width="270" />\n                    </p>\n                {% endif %}\n            </form>\n        </div>\n    </div>\n </body>\n</html>', help_text='HTML Content for the otp page'),
        ),
        migrations.AlterField(
            model_name='portaltemplate',
            name='html_password',
            field=models.TextField(default='<!DOCTYPE html>\n<html>\n <head>\n    <meta charset="utf-8" />\n    <title>Vulture Change Password</title>\n    <link rel="stylesheet" href="/templates/static/html/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">\n    <style>{{style}}</style>\n </head>\n <body>\n    <div class="container">\n        <div class="card card-container" style="text-align:center;">\n            <form action=\'\' method=\'POST\' autocomplete=\'off\' class=\'form-signin\'>\n                <img id="vulture_img" src="{{image_1}}"/>\n                {% if error_message %}\n                    <div class="alert alert-danger">{{error_message}}</div>\n                {% endif %}\n                {% if dialog_change %}\n                    <p>Hello <b>{{username}}</b></p>\n                    <p>Please fill the form to change your current password :</p>\n                    {% if reset_password_key %}\n                    <input type="text" class="form-control" name="{{reset_password_name}}" value="{{reset_password_key}}"/>\n                    {% else %}\n                    <input type="password" class="form-control" placeholder="Old password" name="{{input_password_old}}"/>\n                    {% endif %}\n                    <input type="password" class="form-control" placeholder="New password" name="{{input_password_1}}"/>\n                    <input type="password" class="form-control" placeholder="Confirmation" name="{{input_password_2}}"/>\n                    <button class="btn btn-lg btn-warning btn-block btn-signin" type="submit">Ok</button>\n\n                {% elif dialog_lost %}\n                    <p>Please enter an email address to reset your password:</p>\n                    <input type="email" class="form-control" placeholder="Email" name="{{input_email}}"/>\n                    <button class="btn btn-lg btn-warning btn-block btn-signin" type="submit">Ok</button>\n                    \n                {% endif %}\n            </form>\n        </div>\n    </div>\n </body>\n</html>', help_text='HTML Content for the password change page'),
        ),
        migrations.AlterField(
            model_name='portaltemplate',
            name='html_registration',
            field=models.TextField(default='<!DOCTYPE html>\n<html>\n <head>\n    <meta charset="utf-8" />\n    <title>Vulture Registration</title>\n    <link rel="stylesheet" href="/templates/static/html/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">\n    <style>{{style}}</style>\n </head>\n <body>\n    <div class="container">\n        <div class="card card-container" style="text-align:center;">\n            {{form_begin}}\n                <img id="vulture_img" src="{{image_1}}"/>\n                {% if error_message %}\n                    <div class="alert alert-danger">{{error_message}}</div>\n                {% endif %}\n                {{captcha}}\n                {{input_captcha}}\n                {% if step2 %}\n                    <p>Please fill the form to register your account :</p>\n                    {{input_username}}\n                    {% if ask_phone %}\n                    {{input_phone}}\n                    {% endif %}\n                    {{input_password_1}}\n                    {{input_password_2}}\n                    {{input_submit}}\n\n                {% elif step1 %}\n                    <p>Please enter your email address to receive the registration mail :</p>\n                    {{input_email}}\n                    {{input_submit}}\n                {% endif %}\n            {{form_end}}\n        </div>\n    </div>\n </body>\n</html>', help_text='HTML Content for registration pages'),
        ),
        migrations.AlterField(
            model_name='portaltemplate',
            name='name',
            field=models.TextField(default='Portal template', help_text='Friendly name to reference the template', unique=True),
        ),
    ]
