# Generated by Django 3.0.5 on 2021-10-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20210812_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthentication',
            name='sso_keep_client_cookies',
            field=models.BooleanField(default=False, help_text="Take client's cookies while executing SSO requests"),
        ),
    ]
