# Generated by Django 3.0.5 on 2022-06-14 13:36

import bson.objectid
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0043_auto_20220701_1831'),
        ('authentication', '0017_auto_20220504_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ldaprepository',
            name='user_smartcardid_attr',
        ),
        migrations.AlterField(
            model_name='openidrepository',
            name='authorization_endpoint',
            field=models.TextField(default='', help_text='', verbose_name='Authorization url'),
        ),
        migrations.AlterField(
            model_name='openidrepository',
            name='end_session_endpoint',
            field=models.TextField(default='', help_text='', verbose_name='Disconnect url'),
        ),
        migrations.AlterField(
            model_name='openidrepository',
            name='issuer',
            field=models.TextField(default='', help_text='', verbose_name='Issuer to use'),
        ),
        migrations.AlterField(
            model_name='openidrepository',
            name='provider',
            field=models.TextField(choices=[('google', 'Google'), ('azure', 'Azure'), ('facebook', 'Facebook'), ('github', 'Github'), ('keycloak', 'Keycloak'), ('gitlab', 'Gitlab'), ('linkedin', 'Linkedin'), ('azureAD', 'Azure AD'), ('MazureAD', 'Microsoft Azure AD'), ('openid', 'OpenID Connect'), ('gov', 'Login.gov'), ('nextcloud', 'Nextcloud'), ('digitalocean', 'DigitalOcean'), ('bitbucket', 'Bitbucket'), ('gitea', 'Gitea'), ('digital_pass', 'Digital Pass')], default='google', help_text='Type of provider', verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='openidrepository',
            name='token_endpoint',
            field=models.TextField(default='', help_text='', verbose_name='Get token url'),
        ),
        migrations.AlterField(
            model_name='openidrepository',
            name='userinfo_endpoint',
            field=models.TextField(default='', help_text='', verbose_name='Get user infos url'),
        ),
        migrations.AlterField(
            model_name='portaltemplate',
            name='html_login',
            field=models.TextField(default='<!DOCTYPE html>\n<html>\n<head>\n    <meta charset="utf-8"/>\n    <title>Vulture Login</title>\n    <link rel="stylesheet" href="/templates/static/html/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">\n    <style>{{style}}</style>\n </head>\n <body>\n    <div class="container">\n        <div class="card card-container">\n            <form action=\'\' method=\'POST\' autocomplete=\'off\' class=\'form-signin\'>\n                <img id="vulture_img" src="{{image_1}}"/>\n                {% if error_message != "" %}\n                  <div class="alert alert-danger" role="alert">{{error_message}}</div>\n                {% endif %}\n                <span id="reauth-email" class="reauth-email"></span>\n                <input type="text" name="{{input_login}}" class="form-control" placeholder="Login" required/>\n                <input type="password" name="{{input_password}}" class="form-control" placeholder="Password" required/>\n                {% if captcha %}\n                    <img id="captcha" src="{{captcha}}"/>\n                    <input type="text" name="{{input_captcha}}" class="form-control" placeholder="Captcha" required/>\n\n                {% endif %}\n                <button class="btn btn-lg btn-warning btn-block btn-signin" type="submit">{{login_submit_field}}</button>\n                {% for repo in openid_repos %}\n                <a href="{{repo.start_url}}">Login with {{repo.name}} ({{repo.provider}})</a><br>\n                {% endfor %}\n                <a href="{{lostPassword}}">Forgotten password ?</a>\n            </form>\n        </div>\n    </div>\n </body>\n</html>', help_text='HTML Content for the login page'),
        ),
        migrations.AlterField(
            model_name='portaltemplate',
            name='html_password',
            field=models.TextField(default='<!DOCTYPE html>\n<html>\n <head>\n    <meta charset="utf-8" />\n    <title>Vulture Change Password</title>\n    <link rel="stylesheet" href="/templates/static/html/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">\n    <style>{{style}}</style>\n </head>\n <body>\n    <div class="container">\n        <div class="card card-container" style="text-align:center;">\n            <form action=\'\' method=\'POST\' autocomplete=\'off\' class=\'form-signin\'>\n                <img id="vulture_img" src="{{image_1}}"/>\n                {% if error_message %}\n                    <div class="alert alert-danger">{{error_message}}</div>\n                {% endif %}\n                {% if dialog_change %}\n                    <p>Hello <b>{{username}}</b></p>\n                    <p>Please fill the form to change your current password :</p>\n                    {% if reset_password_key %}\n                    <input type="hidden" class="form-control" name="{{reset_password_name}}" value="{{reset_password_key}}"/>\n                    {% else %}\n                    <input type="password" class="form-control" placeholder="Old password" name="{{input_password_old}}"/>\n                    {% endif %}\n                    <input type="password" class="form-control" placeholder="New password" name="{{input_password_1}}"/>\n                    <input type="password" class="form-control" placeholder="Confirmation" name="{{input_password_2}}"/>\n                    <button class="btn btn-lg btn-warning btn-block btn-signin" type="submit">Ok</button>\n\n                {% elif dialog_lost %}\n                    <p>Please enter an email address to reset your password:</p>\n                    <input type="email" class="form-control" placeholder="Email" name="{{input_email}}"/>\n                    <button class="btn btn-lg btn-warning btn-block btn-signin" type="submit">Ok</button>\n                    \n                {% endif %}\n            </form>\n        </div>\n    </div>\n </body>\n</html>', help_text='HTML Content for the password change page'),
        ),
        migrations.AlterField(
            model_name='repoattributes',
            name='condition_criterion',
            field=models.TextField(choices=[('equals', 'equals to'), ('not equals', 'does not equal to'), ('exists', 'exists'), ('not exists', 'does not exist'), ('contains', 'contains'), ('not contains', 'does not contain'), ('startswith', 'starts with'), ('endswith', 'ends with')], default='equals'),
        ),
        migrations.AlterField(
            model_name='repoattributes',
            name='condition_var_kind',
            field=models.TextField(choices=[('claim', 'Claim attribute'), ('repo', 'Repository attribute'), ('constant', 'Constant'), ('always', 'Always')], default='claim'),
        ),
        migrations.AlterField(
            model_name='userauthentication',
            name='external_listener',
            field=models.ForeignKey(help_text='Listener used for external portal', null=True, on_delete=django.db.models.deletion.PROTECT, to='services.Frontend', verbose_name='Listen on'),
        ),
        migrations.AlterField(
            model_name='userauthentication',
            name='sso_forward_capture_content',
            field=models.TextField(default='^REGEX to capture (content.*) in SSO Forward Response$', help_text=''),
        ),
        migrations.AlterField(
            model_name='userauthentication',
            name='sso_forward_content',
            field=models.TextField(default='', help_text=''),
        ),
    ]
