# Generated by Django 3.0.5 on 2023-06-07 15:28

import bson.objectid
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_auto_20230602_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthentication',
            name='enable_refresh',
            field=models.BooleanField(default=False, help_text='Enable refresh token provider', verbose_name='Enable OAuth2 refresh token'),
        ),
        migrations.AddField(
            model_name='userauthentication',
            name='enable_rotation',
            field=models.BooleanField(default=True, help_text='Rotate refresh token at every successful request', verbose_name='Enable refresh token rotation'),
        ),
        migrations.AddField(
            model_name='userauthentication',
            name='max_nb_refresh',
            field=models.PositiveIntegerField(default=0, help_text='Number of old refresh token kept in memory', verbose_name='History of expired tokens'),
        ),
    ]
