# Generated by Django 3.2.20 on 2023-08-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_auto_20230607_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldaprepository',
            name='group_objectclasses',
            field=models.JSONField(default=['top', 'groupOfNames'], help_text='List of object classes to use to define new Groups', verbose_name='Group Object classes'),
        ),
        migrations.AddField(
            model_name='ldaprepository',
            name='user_objectclasses',
            field=models.JSONField(default=['top', 'InetOrgPerson'], help_text='List of object classes to use to define new Users', verbose_name='User Object classes'),
        ),
        migrations.AlterField(
            model_name='ldaprepository',
            name='group_member_attr',
            field=models.TextField(default='member', help_text='Attribute which contains list of group members', verbose_name='Members attribute'),
        ),
        migrations.AlterField(
            model_name='ldaprepository',
            name='user_attr',
            field=models.TextField(default='uid', help_text='Attribute which identify user', verbose_name='User main attribute'),
        ),
        migrations.AlterField(
            model_name='ldaprepository',
            name='user_scope',
            field=models.PositiveIntegerField(choices=[(0, 'base (the suffix entry only)'), (1, 'one (one level under suffix)'), (2, 'subtree (all levels under suffix)')], default=0, help_text='Depth of the search operation', verbose_name='User search scope'),
        ),
    ]
