# Generated by Django 4.2.6 on 2023-11-29 15:01

import bson.objectid
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_auto_20231005_0916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RepoAttributes',
        ),
    ]
