# Generated by Django 4.2.6 on 2023-12-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_auto_20231005_0916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RepoAttributes',
        ),
        migrations.AlterField(
            model_name='openidrepository',
            name='jwt_signature_type',
            field=models.TextField(blank=True, choices=[('HS256', 'hmac using sha256'), ('HS384', 'hmac using sha384'), ('HS512', 'hmac using sha512'), ('RS256', 'rsa_pkcs1 using sha256'), ('RS384', 'rsa_pkcs1 using sha384'), ('RS512', 'rsa_pkcs1 using sha512'), ('ES256', 'ecdsa using p256 & sha256'), ('ES384', 'ecdsa using p384 & sha384'), ('ES512', 'ecdsa using p512 & sha512'), ('PS256', 'rsa_pss using mgf1 & sha256'), ('PS384', 'rsa_pss using mgf1 & sha384'), ('PS512', 'rsa_pss using mgf1 & sha512')], default='HS256', help_text='Signature type as given in RFC7518', verbose_name='Signature type'),
        ),
    ]
