# Generated by Django 4.2.7 on 2023-12-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_add_ldapcustomattributemapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openidrepository',
            name='enable_jwt',
            field=models.BooleanField(blank=True, default=False, help_text='JWT used to authenticate/authorize user', verbose_name='Validate JWT'),
        ),
        migrations.AlterField(
            model_name='openidrepository',
            name='jwt_validate_audience',
            field=models.BooleanField(blank=True, default=True, help_text="Be more flexible without verifying who's the token for, used when multiple fqdn need to be reached (default=on)", verbose_name='Validate JWT audience'),
        ),
        migrations.AlterField(
            model_name='userauthentication',
            name='sso_forward_tls_proto',
            field=models.TextField(choices=[('tlsv13', 'TLSv1.3'), ('tlsv12', 'TLSv1.2'), ('tlsv11', 'TLSv1.1'), ('tlsv10', 'TLSv1.0')], default=('tlsv12', 'TLSv1.2'), help_text='Minimal TLS protocol used to connect to SSO url', verbose_name='TLS minimal accepted version'),
        )
    ]
