# Generated by Django 2.1.3 on 2019-04-01 07:58

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('toolkit', '0001_initial'),
        ('system', '0001_initial'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='tls_profile',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='system.TLSProfile'),
        ),
        migrations.AddField(
            model_name='backend',
            name='headers',
            field=djongo.models.fields.ArrayReferenceField(help_text='Header rules', null=True, on_delete=django.db.models.deletion.CASCADE, to='toolkit.Header'),
        ),
        migrations.AlterUniqueTogether(
            name='server',
            unique_together={('target', 'port')},
        ),
        migrations.AddField(
            model_name='logomrelp',
            name='x509_certificate',
            field=models.ForeignKey(default=None, help_text='X509Certificate object to use.', null=True, on_delete=django.db.models.deletion.CASCADE, to='system.X509Certificate'),
        ),
        migrations.AddField(
            model_name='logommongodb',
            name='x509_certificate',
            field=models.ForeignKey(default=None, help_text='X509Certificate object to use.', null=True, on_delete=django.db.models.deletion.CASCADE, to='system.X509Certificate'),
        ),
        migrations.AddField(
            model_name='logomelasticsearch',
            name='x509_certificate',
            field=models.ForeignKey(default=None, help_text='X509Certificate object to use.', null=True, on_delete=django.db.models.deletion.CASCADE, to='system.X509Certificate'),
        ),
    ]
