# Generated by Django 2.1.3 on 2019-04-01 08:38

import django.core.validators
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20190401_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Parser', help_text='Custom name of the current object', unique=True, verbose_name='Friendly name')),
                ('rulebase', models.TextField(default='version=2\nrule=:%timestamp_app:float{"format": "number"}%', help_text='Parser rules', verbose_name='Rulebase')),
                ('to_test', models.TextField(default='1553103776.045449327', help_text='Lines to apply te parser on', verbose_name='Lines to test')),
                ('tags', djongo.models.fields.JSONField(default=[], help_text='Tags to set on this object for search', verbose_name=models.SlugField(default=''))),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='source',
            field=models.GenericIPAddressField(default='5.6.7.8', help_text='IP address to assign to sources'),
        ),
        migrations.AlterField(
            model_name='backend',
            name='timeout_server',
            field=models.PositiveIntegerField(default=2, help_text='HTTP request Timeout', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3600)], verbose_name='Timeout'),
        ),
        migrations.AlterField(
            model_name='server',
            name='weight',
            field=models.PositiveIntegerField(default=1, help_text='', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(256)]),
        ),
        migrations.AlterUniqueTogether(
            name='server',
            unique_together=set(),
        ),
    ]
