# Generated by Django 2.1.3 on 2019-04-01 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20190401_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='source',
            field=models.GenericIPAddressField(default='', help_text='IP address to assign to sources'),
        ),
        migrations.AlterField(
            model_name='server',
            name='weight',
            field=models.PositiveIntegerField(default=1, help_text='', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(256)]),
        ),
    ]
