# Generated by Django 2.1.3 on 2019-05-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20190401_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='backend',
            name='http_backend_dir',
            field=models.TextField(default='/', help_text='Servers directory to prefix in front of requests uri', verbose_name='Servers directory'),
        ),
    ]
