# Generated by Django 2.1.3 on 2019-06-17 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_auto_20190515_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backend',
            name='timeout_server',
            field=models.PositiveIntegerField(default=60, help_text='HTTP request Timeout', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3600)], verbose_name='Timeout'),
        ),
    ]
