# Generated by Django 2.1.3 on 2019-08-29 10:41

import django.core.validators
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_auto_20190617_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parser",
            name="tags"
        ),
        migrations.AddField(
            model_name='parser',
            name='tags',
            field=djongo.models.fields.JSONField(blank=True, default=[], help_text='Tags to set on this object for search', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='server',
            name='weight',
            field=models.PositiveIntegerField(default=1, help_text='', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(256)]),
        ),
    ]
