# Generated by Django 2.1.3 on 2019-11-19 03:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_auto_20190829_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='logomfile',
            name='retention_time',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='logomfile',
            name='rotation_period',
            field=models.TextField(choices=[('daily', 'Every day'), ('weekly', 'Every week'), ('monthly', 'Every month'), ('yearly', 'Every year')], default='daily'),
        ),
        migrations.AddField(
            model_name='logomfile',
            name='stock_as_raw',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reputationcontext',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='reputationcontext',
            name='filename',
            field=models.FilePathField(default='', path='/var/db/darwin', unique=True),
        ),
        migrations.AddField(
            model_name='reputationcontext',
            name='internal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reputationcontext',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reputationcontext',
            name='nb_netset',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reputationcontext',
            name='nb_unique',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reputationcontext',
            name='db_type',
            field=models.TextField(choices=[('ipv4', 'IPv4 MMDB'), ('ipv6', 'IPv6 MMDB'), ('ipv4_netset', 'IPv4 Netset'), ('ipv6_netset', 'IPv6 Netset'), ('domain', 'Host/Domain names'), ('GeoIP', 'GeoIP')], default='ipv4', help_text='Type of database', verbose_name='Database type'),
        ),
        migrations.AlterField(
            model_name='reputationcontext',
            name='name',
            field=models.TextField(default='Reputation context', help_text='Custom name of the current object', verbose_name='Friendly name'),
        )
    ]
