# Generated by Django 2.1.3 on 2020-09-15 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_auto_20200602_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portaltemplate',
            name='images',
        ),
        migrations.RemoveField(
            model_name='templateimage',
            name='content',
        ),
        migrations.AlterField(
            model_name='server',
            name='weight',
            field=models.PositiveIntegerField(default=1, help_text='', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(256)]),
        ),
    ]
