# Generated by Django 2.1.3 on 2020-09-15 15:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_auto_20200828_1451'),
        ('applications', '0010_auto_20200602_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='logomelasticsearch',
            name='output_ipaddress',
            field=models.ForeignKey(default=None, help_text='IPAddress to use to connect to foreign server', on_delete=django.db.models.deletion.PROTECT, to='system.NetworkAddress'),
        ),
        migrations.AddField(
            model_name='logomfwd',
            name='output_ipaddress',
            field=models.ForeignKey(default=None, help_text='IPAddress to use to connect to foreign server', on_delete=django.db.models.deletion.PROTECT, to='system.NetworkAddress'),
        ),
        migrations.AddField(
            model_name='logomhiredis',
            name='output_ipaddress',
            field=models.ForeignKey(default=None, help_text='IPAddress to use to connect to foreign server', on_delete=django.db.models.deletion.PROTECT, to='system.NetworkAddress'),
        ),
        migrations.AddField(
            model_name='logommongodb',
            name='output_ipaddress',
            field=models.ForeignKey(default=None, help_text='IPAddress to use to connect to foreign server', on_delete=django.db.models.deletion.PROTECT, to='system.NetworkAddress'),
        ),
        migrations.AddField(
            model_name='logomrelp',
            name='output_ipaddress',
            field=models.ForeignKey(default=None, help_text='IPAddress to use to connect to foreign server', on_delete=django.db.models.deletion.PROTECT, to='system.NetworkAddress'),
        )
    ]
