# Generated by Django 3.0.5 on 2021-04-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_auto_20210414_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='logomfwd',
            name='send_as_raw',
            field=models.BooleanField(default=False),
        ),
    ]
