# Generated by Django 3.0.5 on 2022-05-05 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_logomfwd_send_as_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='weight',
            field=models.PositiveIntegerField(default=1, help_text='', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(256)]),
        ),
    ]
