# Generated by Django 3.0.5 on 2022-08-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_auto_20220505_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='logomelasticsearch',
            name='ratelimit_burst',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logomelasticsearch',
            name='ratelimit_interval',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logomfwd',
            name='ratelimit_burst',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logomfwd',
            name='ratelimit_interval',
            field=models.PositiveIntegerField(blank=True, null=True),
        )
    ]
