# Generated by Django 3.0.5 on 2023-06-27 16:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_auto_20220825_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='logom',
            name='enable_disk_assist',
            field=models.BooleanField(default=False, help_text='Enable disk-assisted queue on failure', verbose_name='Enable disk queue on failure'),
        ),
        migrations.AddField(
            model_name='logom',
            name='enable_retry',
            field=models.BooleanField(default=False, help_text='Enable retry when failure occurs', verbose_name='Enable retry on failure'),
        ),
        migrations.AddField(
            model_name='logom',
            name='high_watermark',
            field=models.PositiveIntegerField(default=8000, help_text='Target of the high watermark', null=True, validators=[django.core.validators.MinValueValidator(100)], verbose_name='High watermark target'),
        ),
        migrations.AddField(
            model_name='logom',
            name='low_watermark',
            field=models.PositiveIntegerField(default=6000, help_text='Set the value of the low watermark', null=True, validators=[django.core.validators.MinValueValidator(100)], verbose_name='Low watermark target'),
        ),
        migrations.AddField(
            model_name='logom',
            name='max_disk_space',
            field=models.IntegerField(default=1024, help_text='Limit the maximum disk space used by the queue in MB', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Max disk space used by the queue in MB'),
        ),
        migrations.AddField(
            model_name='logom',
            name='max_file_size',
            field=models.IntegerField(default=256, help_text='Set the value of the queue in MB', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Max file size of the queue in MB'),
        ),
        migrations.AddField(
            model_name='logom',
            name='queue_size',
            field=models.PositiveIntegerField(default=10000, help_text='Size of the queue when failure occurs', validators=[django.core.validators.MinValueValidator(100)], verbose_name='Size of the queue in nb of message'),
        ),
    ]
