# Generated by Django 4.2.11 on 2024-03-15 05:27

import django.core.validators
from django.db import migrations, models
import djongo.models.fields

enabled_logom = {}

def save_enabled_state(apps, schema_editor):
    logomfile_model = apps.get_model("applications", "LogOMFile")
    logomrelp_model = apps.get_model("applications", "LogOMRELP")
    logomhiredis_model = apps.get_model("applications", "LogOMHIREDIS")
    logomfwd_model = apps.get_model("applications", "LogOMFWD")
    logomelastic_model = apps.get_model("applications", "LogOMElasticSearch")
    logommongodb_model = apps.get_model("applications", "LogOMMongoDB")
    logomkafka_model = apps.get_model("applications", "LogOMKAFKA")
    db_alias = schema_editor.connection.alias
    logomfile = logomfile_model.objects.using(db_alias)
    logomrelp = logomrelp_model.objects.using(db_alias)
    logomhiredis = logomhiredis_model.objects.using(db_alias)
    logomfwd = logomfwd_model.objects.using(db_alias)
    logomelastic = logomelastic_model.objects.using(db_alias)
    logommongodb = logommongodb_model.objects.using(db_alias)
    logomkafka = logomkafka_model.objects.using(db_alias)

    for filefwd in logomfile.all():
        enabled_logom[filefwd.name] = filefwd.enabled
    for logomrelp in logomrelp.all():
        enabled_logom[logomrelp.name] = logomrelp.enabled
    for logomhiredis in logomhiredis.all():
        enabled_logom[logomhiredis.name] = logomhiredis.enabled
    for logomfwd in logomfwd.all():
        enabled_logom[logomfwd.name] = logomfwd.enabled
    for logomelastic in logomelastic.all():
        enabled_logom[logomelastic.name] = logomelastic.enabled
    for logommongodb in logommongodb.all():
        enabled_logom[logommongodb.name] = logommongodb.enabled
    for logomkafka in logomkafka.all():
        enabled_logom[logomkafka.name] = logomkafka.enabled

def restore_enabled_state(apps, schema_editor):
    logfwd_model = apps.get_model("applications", "LogOM")
    db_alias = schema_editor.connection.alias
    logfwd = logfwd_model.objects.using(db_alias)

    for fwd in logfwd.all():
        fwd.enabled = enabled_logom[fwd.name]
        fwd.save()

class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0023_logomhiredis_expire_key_logomhiredis_mode_and_more'),
    ]

    operations = [
        migrations.RunPython(save_enabled_state, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='logomelasticsearch',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='logomfile',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='logomfwd',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='logomhiredis',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='logomkafka',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='logommongodb',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='logomrelp',
            name='enabled',
        ),
        migrations.AddField(
            model_name='logom',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(restore_enabled_state, migrations.RunPython.noop),
    ]
