# Generated by Django 4.2.11 on 2025-06-02 08:10

from django.db import migrations, models
import django.db.models.deletion


existing_certificates = {}
new_profiles = {}

def save_x509_certificate(apps, schema_editor):
    logomelasticsearch_model = apps.get_model("applications", "logomelasticsearch")
    db_alias = schema_editor.connection.alias
    logomelasticsearch = logomelasticsearch_model.objects.using(db_alias)

    for logom in logomelasticsearch.filter(x509_certificate__isnull=False):
        existing_certificates[logom.id] = logom.x509_certificate

def create_tls_profile(apps, schema_editor):
    tls_profile_model = apps.get_model("system", "tlsprofile")
    db_alias = schema_editor.connection.alias
    tls_profile = tls_profile_model.objects.using(db_alias)

    for id, certificate in existing_certificates.items():
        if certificate.is_ca_cert() is True:
            new_profile, created = tls_profile.get_or_create(
                name=f"TLS Profile {certificate}",
                verify_client="required",
                ca_cert=certificate
            )
        else:
            new_profile, created = tls_profile.get_or_create(
                name=f"TLS Profile {certificate}",
                x509_certificate=certificate
            )
        new_profile.save_conf()
        new_profiles[id] = new_profile

def inject_tls_profile(apps, schema_editor):
    logomelasticsearch_model = apps.get_model("applications", "logomelasticsearch")
    db_alias = schema_editor.connection.alias
    logomelasticsearch = logomelasticsearch_model.objects.using(db_alias)

    for logom in logomelasticsearch.all():
        if new_profiles[logom.id]:
            # inject the new tls_profile
            logom.tls_profile = new_profiles[logom.id]
            logom.save()


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0025_auto_20241210_1046'),
    ]

    operations = [
        migrations.RunPython(save_x509_certificate, migrations.RunPython.noop),
        migrations.RunPython(create_tls_profile, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='logomelasticsearch',
            name='x509_certificate',
        ),
        migrations.AddField(
            model_name='logomelasticsearch',
            name='tls_profile',
            field=models.ForeignKey(blank=True, default=None, help_text='TLSProfile object to use.', null=True, on_delete=django.db.models.deletion.CASCADE, to='system.tlsprofile', verbose_name='Use a TLS Profile'),
        ),
        migrations.RunPython(inject_tls_profile, migrations.RunPython.noop),
    ]
