# Generated by Django 4.2.24 on 2025-11-04 16:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0028_alter_tlsprofile_ca_cert_and_more'),
        ('applications', '0027_add_logomsentinel'),
    ]

    operations = [
        migrations.AddField(
            model_name='logomhiredis',
            name='tls_profile',
            field=models.ForeignKey(blank=True, default=None, help_text='TLSProfile object to use.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='system.tlsprofile', verbose_name='Use a TLS Profile'),
        ),
    ]
