# Generated by Django 4.2.26 on 2026-06-18 09:25

from django.db import migrations, models


def migrate_compression_mode(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    logomfwd_model = apps.get_model("applications", "logomfwd")
    logomfwd = logomfwd_model.objects.using(db_alias)

    logomfwd.filter(zip_level__gt=0).update(compression_mode="single")


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0028_logomhiredis_redis_tls_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logomfwd',
            name='compression_mode',
            field=models.TextField(choices=[('none', 'No compression'), ('single', 'Compress message by message (no delay)'), ('stream:always', 'Compress TCP data flow (delay may occur when sending)')], default='none', help_text='stream:always option requires a compatible destination.', verbose_name='Compression mode'),
        ),
        migrations.AddField(
            model_name='logomfwd',
            name='flush_on_txend',
            field=models.BooleanField(default=True, help_text='Not flushing compression buffer can improve performances on high EPS only.', verbose_name='Flush on TX End (disable on very high throughput only)'),
        ),
        migrations.RunPython(migrate_compression_mode, migrations.RunPython.noop),
    ]
