# Generated by Django 2.1.3 on 2019-05-15 16:56

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('darwin', '0002_filterpolicy_cache_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefenderRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.TextField()),
                ('ids', models.JSONField(default=[], verbose_name=django.db.models.fields.IntegerField)),
                ('key', models.TextField()),
                ('value', models.TextField()),
                ('url', models.TextField()),
                ('matched_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DefenderRuleset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('raw_rules', models.TextField()),
                ('rules', models.ManyToManyField(to='darwin.DefenderRule')),
            ],
        ),
        migrations.AddField(
            model_name='darwinpolicy',
            name='defender_ruleset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='darwin.DefenderRuleset'),
        ),
    ]
