# Generated by Django 2.1.3 on 2019-07-01 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20190701_1353'),
        ('darwin', '0003_auto_20190515_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistWhitelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('rule', models.TextField()),
                ('type_rule', models.TextField(default='blacklist')),
                ('name', models.TextField(default='')),
                ('frontend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Frontend')),
            ],
        ),
    ]
