# Generated by Django 2.1.3 on 2019-09-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darwin', '0006_auto_20190829_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionpolicy',
            name='name',
            field=models.TextField(default='Custom Inspection Policy', help_text='Friendly name for your inspection policy', unique=True),
        ),
    ]
