# Generated by Django 2.1.3 on 2019-12-18 09:55

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('darwin', '0008_auto_20191119_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterpolicy',
            name='cache_size',
            field=models.PositiveIntegerField(default=0, help_text='The cache size to use for caching darwin requests.', verbose_name='Cache size'),
        ),
        migrations.AlterField(
            model_name='filterpolicy',
            name='log_level',
            field=models.TextField(choices=[('ERROR', 'Error'), ('WARNING', 'Warning'), ('INFO', 'Informational'), ('DEBUG', 'Debug')], default='WARNING'),
        ),
        migrations.AlterField(
            model_name='filterpolicy',
            name='config',
            field=djongo.models.fields.DictField(default={'alert_redis_channel_name': 'darwin.alerts', 'alert_redis_list_name': 'darwin_alerts', 'log_file_path': '/var/log/darwin/alerts.log', 'redis_socket_path': '/var/sockets/redis/redis.sock'}),
        )
    ]
