# Generated by Django 3.0.5 on 2021-04-23 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darwin', '0010_auto_20201118_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesscontrol',
            name='enabled',
        ),
    ]
