# Generated by Django 3.0.5 on 2022-06-14 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_remove_workflow_defender_policy'),
        ('darwin', '0011_remove_accesscontrol_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defenderpolicy',
            name='defender_ruleset',
        ),
        migrations.DeleteModel(
            name='DefenderProcessRule',
        ),
        migrations.DeleteModel(
            name='DefenderProcessRuleJob',
        ),
        migrations.RemoveField(
            model_name='defenderruleset',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='inspectionpolicy',
            name='rules',
        ),
        migrations.AlterUniqueTogether(
            name='logviewerconfiguration',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='logviewerconfiguration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='logviewersearches',
            name='user',
        ),
        migrations.DeleteModel(
            name='DefenderPolicy',
        ),
        migrations.DeleteModel(
            name='DefenderRule',
        ),
        migrations.DeleteModel(
            name='DefenderRuleset',
        ),
        migrations.DeleteModel(
            name='InspectionPolicy',
        ),
        migrations.DeleteModel(
            name='InspectionRule',
        ),
        migrations.DeleteModel(
            name='LogViewerConfiguration',
        ),
        migrations.DeleteModel(
            name='LogViewerSearches',
        ),
    ]
