# Generated by Django 4.2.11 on 2024-03-06 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darwin', '0012_auto_20220614_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterpolicy',
            name='filter_type',
        ),
        migrations.RemoveField(
            model_name='filterpolicy',
            name='next_filter',
        ),
        migrations.RemoveField(
            model_name='filterpolicy',
            name='policy',
        ),
        migrations.DeleteModel(
            name='DarwinBuffering',
        ),
        migrations.DeleteModel(
            name='DarwinFilter',
        ),
        migrations.DeleteModel(
            name='DarwinPolicy',
        ),
        migrations.DeleteModel(
            name='FilterPolicy',
        ),
    ]
