# Generated by Django 2.1.3 on 2019-04-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='is_scanner',
            field=models.BooleanField(default=False),
        ),
    ]
