# Generated by Django 2.1.3 on 2019-05-10 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_config_is_scanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZFS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('used', models.TextField()),
                ('avail', models.TextField()),
                ('refer', models.TextField()),
                ('mount', models.TextField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Node')),
            ],
        ),
    ]
