# Generated by Django 2.1.3 on 2019-05-27 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_zfs'),
    ]

    operations = [
        migrations.CreateModel(
            name='VM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('datastore', models.TextField()),
                ('loader', models.TextField()),
                ('cpu', models.TextField()),
                ('ram', models.TextField()),
                ('vnc', models.TextField()),
                ('autostart', models.TextField()),
                ('status', models.TextField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Node')),
            ],
        ),
    ]
