# Generated by Django 2.1.3 on 2019-07-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20190625_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='logs_ttl',
            field=models.PositiveIntegerField(default=86400, help_text='Retention period in seconds, of PF logs and Internal logs into cluster database', verbose_name='Retention period of internal database logs (seconds)'),
        ),
    ]
