# Generated by Django 2.1.3 on 2019-09-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_config_logs_ttl'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='chameleon_apikey',
            field=models.TextField(blank=True, default=''),
        ),
    ]
