# Generated by Django 2.1.3 on 2019-11-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_config_chameleon_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='pf_limit_states',
            field=models.IntegerField(default=500000),
        ),
    ]
