# Generated by Django 2.1.3 on 2019-11-23 00:47

from django.db import migrations, models
from system.cluster.models import Cluster
from toolkit.postgresql.postgres_base import PostgresBase


def fill_system_node_columns(apps, schema_editor):
    p = PostgresBase()
    p.connect_primary()

    # If the node is not yet installed, no need to drop constraints
    if not p.conn:
        return

    try:
        # Check if the database and table exist
        if not p.database_exists('vulture'):
            print("Database 'vulture' does not exist, skipping columns adding")
            return
        with p.conn.cursor() as cursor:
            cursor.execute("SET search_path TO vulture")

        if not p.table_exists('system_node'):
            print("Table 'system_node' does not exist, skipping columns adding")
            return

        cursor.execute("ALTER TABLE system_node ADD COLUMN pf_custom_param_config TEXT")
        cursor.execute("ALTER TABLE system_node ADD COLUMN pf_custom_nat_config TEXT")
        cursor.execute("ALTER TABLE system_node ADD COLUMN pf_custom_rdr_config TEXT")
        cursor.execute("ALTER TABLE system_node ADD COLUMN backends_outgoing_ip INET")
        cursor.execute("ALTER TABLE system_node ADD COLUMN logom_outgoing_ip INET")
        cursor.execute("ALTER TABLE system_node ADD COLUMN _vstate TEXT;")
        cursor.execute("ALTER TABLE system_node ADD COLUMN heartbeat TIMESTAMP WITH TIME ZONE;")

    except Exception as e:
        if p.conn:
            p.conn.rollback()

        import logging
        logger = logging.getLogger('system')
        logger.error(f"Failed to remove server target/port uniqueness constraint: {e}", exc_info=1)



def forwards_func(apps, schema_editor):
    logomhiredis_model = apps.get_model("applications", "LogOMHIREDIS")
    db_alias = schema_editor.connection.alias
    node = Cluster.get_current_node()
    # If node not boostrapped
    if not node:
        return
    logomhiredis_objects = logomhiredis_model.objects.using(db_alias)

    try:
        redis_internal_dashboard = logomhiredis_objects.get(name="Internal_Dashboard", internal=True)
        node.pstats_forwarders.add(redis_internal_dashboard)
        node.save()
    except:
        print("Internal_Dashboard forwarder not found.")


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20191119_0339'),
    ]

    operations = [
        migrations.RunPython(fill_system_node_columns, migrations.RunPython.noop),
        migrations.AddField(
            model_name='node',
            name='pstats_forwarders',
            field=models.ManyToManyField(help_text='Log forwarders used to send impstats logs', null=True, to='applications.LogOM', verbose_name='Send rsyslog pstats logs to')
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop)
    ]
