# Generated by Django 2.1.3 on 2020-08-28 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_auto_20200518_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkaddress',
            name='fib',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='networkaddress',
            name='vlan',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='networkaddress',
            name='vlandev',
            field=models.ForeignKey(blank=True, help_text='Underlying NIC for VLAN', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='networkaddress_vlandev', to='system.NetworkInterfaceCard', verbose_name='Vlan device'),
        ),
    ]
