# Generated by Django 2.1.3 on 2020-09-15 15:56

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    node_model = apps.get_model("system", "Node")
    db_alias = schema_editor.connection.alias
    node_objects = node_model.objects.using(db_alias)

    for node in node_objects.all():
        if not node.backends_outgoing_ip or node.logom_outgoing_ip:
            if not node.backends_outgoing_ip:
                node.backends_outgoing_ip = node.management_ip
            if not node.logom_outgoing_ip:
                node.logom_outgoing_ip = node.management_ip
        node.save()
        print("Node {} successfully updated.".format(node.name))


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_auto_20200828_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='backends_outgoing_ip',
            field=models.GenericIPAddressField(default='', help_text='IP used for masquerading backends packets'),
        ),
        migrations.AddField(
            model_name='node',
            name='logom_outgoing_ip',
            field=models.GenericIPAddressField(default='', help_text='IP used for masquerading log forwarders packets'),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop)
    ]
