# Generated by Django 2.1.3 on 2020-09-15 15:56

from django.db import migrations, models
from toolkit.postgresql.postgres_base import PostgresBase

def drop_system_node_columns(apps, schema_editor):
    p = PostgresBase()
    p.connect_primary()

    # If the node is not yet installed, no need to drop constraints
    if not p.conn:
        return

    try:
        # Check if the database and table exist
        if not p.database_exists('vulture'):
            print("Database 'vulture' does not exist, skipping columns adding")
            return
        with p.conn.cursor() as cursor:
            cursor.execute("SET search_path TO vulture")

        if not p.table_exists('system_node'):
            print("Table 'system_node' does not exist, skipping columns adding")
            return

        cursor.execute("ALTER TABLE system_node DROP COLUMN backends_outgoing_ip")
        cursor.execute("ALTER TABLE system_node DROP COLUMN logom_outgoing_ip")

    except Exception as e:
        if p.conn:
            p.conn.rollback()

        import logging
        logger = logging.getLogger('system')
        logger.error(f"Failed to remove server target/port uniqueness constraint: {e}", exc_info=1)


def forwards_func(apps, schema_editor):
    node_model = apps.get_model("system", "Node")
    db_alias = schema_editor.connection.alias
    node_objects = node_model.objects.using(db_alias)

    for node in node_objects.all():
        if not node.backends_outgoing_ip or node.logom_outgoing_ip:
            if not node.backends_outgoing_ip:
                node.backends_outgoing_ip = node.management_ip
            if not node.logom_outgoing_ip:
                node.logom_outgoing_ip = node.management_ip
        node.save()
        print("Node {} successfully updated.".format(node.name))


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_auto_20200828_1451'),
    ]

    operations = [
        migrations.RunPython(drop_system_node_columns, migrations.RunPython.noop),
        migrations.AddField(
            model_name='node',
            name='backends_outgoing_ip',
            field=models.GenericIPAddressField(default='', help_text='IP used for masquerading backends packets'),
        ),
        migrations.AddField(
            model_name='node',
            name='logom_outgoing_ip',
            field=models.GenericIPAddressField(default='', help_text='IP used for masquerading log forwarders packets'),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop)
    ]
