# Generated by Django 2.1.3 on 2020-10-05 19:58

from django.db import migrations, models
import djongo.models.fields

def forwards_func(apps, schema_editor):
    tls_model = apps.get_model("system", "TLSProfile")
    db_alias = schema_editor.connection.alias
    tls_objects = tls_model.objects.using(db_alias)

    for tls in tls_objects.all():
        if tls.compatibility == "modern":
            tls.compatibility = "advanced"
        elif tls.compatibility == "intermediate":
            tls.compatibility = "broad"
        elif tls.compatibility == "old":
            tls.compatibility = "widest"
        else:
            continue
        print("TLS profile '{}' compatibility updated to {}".format(tls.name, tls.compatibility))
        tls.save()


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_auto_20200915_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlsprofile',
            name='cipher_suite',
            field=models.TextField(default='TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256', help_text='Allowed protocol ciphers.'),
        ),
        migrations.AlterField(
            model_name='tlsprofile',
            name='compatibility',
            field=models.TextField(choices=[('advanced', 'Advanced (A)'), ('broad', 'Broad Compatibility (B)'), ('widest', 'Widest Compatibility (C)'), ('legacy', 'Legacy (D)'), ('custom', 'Custom')], default='broad', help_text='Compatibility of web browsers.'),
        ),
        migrations.AlterField(
            model_name='tlsprofile',
            name='protocols',
            field=djongo.models.fields.JSONField(default=['tlsv12'], help_text='Allowed protocol ciphers.', verbose_name=models.TextField(choices=[('tlsv13', 'TLSv1.3'), ('tlsv12', 'TLSv1.2'), ('tlsv11', 'TLSv1.1'), ('tlsv10', 'TLSv1.0'), ('sslv3', 'SSLv3')])),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop)
    ]
