# Generated by Django 2.1.3 on 2021-02-04 03:40

from django.db import migrations, models
from toolkit.postgresql.postgres_base import PostgresBase

def drop_system_node_columns(apps, schema_editor):
    p = PostgresBase()
    p.connect_primary()

    # If the node is not yet installed, no need to drop constraints
    if not p.conn:
        return

    try:
        # Check if the database and table exist
        if not p.database_exists('vulture'):
            print("Database 'vulture' does not exist, skipping columns adding")
            return
        with p.conn.cursor() as cursor:
            cursor.execute("SET search_path TO vulture")

        if not p.table_exists('system_node'):
            print("Table 'system_node' does not exist, skipping columns adding")
            return

        cursor.execute("ALTER TABLE system_node DROP COLUMN pf_custom_nat_config")
        cursor.execute("ALTER TABLE system_node DROP COLUMN pf_custom_param_config")
        cursor.execute("ALTER TABLE system_node DROP COLUMN pf_custom_rdr_config")

    except Exception as e:
        if p.conn:
            p.conn.rollback()

        import logging
        logger = logging.getLogger('system')
        logger.error(f"Failed to remove server target/port uniqueness constraint: {e}", exc_info=1)


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_auto_20201005_1958'),
    ]

    operations = [
        migrations.RunPython(drop_system_node_columns, migrations.RunPython.noop),
        migrations.AddField(
            model_name='node',
            name='pf_custom_nat_config',
            field=models.TextField(blank=True, default='### Custom NAT rules\n'),
        ),
        migrations.AddField(
            model_name='node',
            name='pf_custom_param_config',
            field=models.TextField(blank=True, default='### Custom global parameters\n'),
        ),
        migrations.AddField(
            model_name='node',
            name='pf_custom_rdr_config',
            field=models.TextField(blank=True, default='### Custom RDR rules\n'),
        ),
    ]
