# Generated by Django 2.1.3 on 2021-01-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_auto_20210204_0340'),
    ]

    operations = [
        migrations.RemoveField(model_name="tlsprofile", name="protocols"),
        migrations.AddField(
            model_name='tlsprofile',
            name='protocols',
            field=models.JSONField(default=['tlsv12'], help_text='Allowed protocol ciphers.', verbose_name=models.TextField(choices=[('tlsv13', 'TLSv1.3'), ('tlsv12', 'TLSv1.2'), ('tlsv11', 'TLSv1.1'), ('tlsv10', 'TLSv1.0')])),
        ),
    ]
