# Generated by Django 3.0.5 on 2023-02-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_auto_20220505_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenants',
            name='name',
            field=models.TextField(default='ACME_Corporation', unique=True),
        ),
    ]
