# Generated by Django 3.0.5 on 2023-02-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_auto_20230216_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkaddress',
            name='carp_vhid',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='networkaddress',
            name='fib',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='networkaddress',
            name='vlan',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
