# Generated by Django 3.2.20 on 2023-08-10 13:49

from django.db import migrations, models
import django.utils.timezone
from toolkit.postgresql.postgres_base import PostgresBase


def drop_system_node_columns(apps, schema_editor):
    p = PostgresBase()
    p.connect_primary()

    # If the node is not yet installed, no need to drop constraints
    if not p.conn:
        return

    try:
        # Check if the database and table exist
        if not p.database_exists('vulture'):
            print("Database 'vulture' does not exist, skipping columns adding")
            return
        with p.conn.cursor() as cursor:
            cursor.execute("SET search_path TO vulture")

        if not p.table_exists('system_node'):
            print("Table 'system_node' does not exist, skipping columns adding")
            return

        cursor.execute("ALTER TABLE system_node DROP COLUMN _vstate")
        cursor.execute("ALTER TABLE system_node DROP COLUMN heartbeat")

    except Exception as e:
        if p.conn:
            p.conn.rollback()

        import logging
        logger = logging.getLogger('system')
        logger.error(f"Failed to remove server target/port uniqueness constraint: {e}", exc_info=1)


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_auto_20230602_2327'),
    ]

    operations = [
        migrations.RunPython(drop_system_node_columns, migrations.RunPython.noop),
        migrations.AddField(
            model_name='node',
            name='_vstate',
            field=models.TextField(choices=[('UP', 'UP'), ('DOWN', 'DOWN'), ('MAINTENANCE', 'MAINTENANCE')], default='UP', help_text='Node state'),
        ),
        migrations.AddField(
            model_name='node',
            name='heartbeat',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last node heartbeat'),
        ),
    ]
