# Generated by Django 3.2.20 on 2023-08-10 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_auto_20230602_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='_vstate',
            field=models.TextField(choices=[('UP', 'UP'), ('DOWN', 'DOWN'), ('MAINTENANCE', 'MAINTENANCE')], default='UP', help_text='Node state'),
        ),
        migrations.AddField(
            model_name='node',
            name='heartbeat',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last node heartbeat'),
        ),
    ]
