# Generated by Django 3.2.20 on 2023-07-19 21:39

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0021_auto_20230810_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlsprofile',
            name='protocols',
            field=djongo.models.fields.JSONField(default=['tlsv13', 'tlsv12'], help_text='Allowed protocol ciphers.', verbose_name=models.TextField(choices=[('tlsv13', 'TLSv1.3'), ('tlsv12', 'TLSv1.2'), ('tlsv11', 'TLSv1.1'), ('tlsv10', 'TLSv1.0')])),
        ),
    ]
