# Generated by Django 4.2.21 on 2025-06-03 08:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0026_alter_x509certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagequeue',
            name='run_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
