# Generated by Django 4.2.23 on 2025-08-18 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0027_messagequeue_run_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlsprofile',
            name='ca_cert',
            field=models.ForeignKey(help_text="CA certificate used to verify peer's certificate if verify != none.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ca_cert_of', to='system.x509certificate', verbose_name="Peer's CA certificate"),
        ),
        migrations.AlterField(
            model_name='tlsprofile',
            name='verify_client',
            field=models.TextField(choices=[('none', 'No'), ('optional', 'Optional'), ('required', 'Required')], default='none', help_text="If set to 'none', peer certificate is not requested. This is the default. In other cases, a peer certificate is requested.", verbose_name='Verify peer certificate'),
        ),
        migrations.AlterField(
            model_name='tlsprofile',
            name='x509_certificate',
            field=models.ForeignKey(blank=True, help_text='X509Certificate object to use.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_of', to='system.x509certificate', verbose_name='My certificate'),
        ),
    ]
