# Generated by Django 2.1.3 on 2019-04-01 07:58

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='VultureOS')),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FilePathField(path='/var/db/darwin/', unique=True)),
                ('label', models.TextField()),
                ('description', models.TextField()),
                ('last_update', models.DateTimeField()),
                ('nb_netset', models.IntegerField()),
                ('nb_unique', models.IntegerField()),
                ('type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Node')),
            ],
        ),
        migrations.CreateModel(
            name='RSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('date', models.DateTimeField()),
                ('level', models.TextField()),
                ('content', models.TextField()),
                ('ack', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='monitor',
            name='services',
            field=djongo.models.fields.ArrayReferenceField(default=[], on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='gui.ServiceStatus'),
        ),
    ]
