# Generated by Django 2.1.3 on 2019-05-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicestatus',
            name='friendly_name',
            field=models.TextField(default=''),
        ),
    ]
