# Generated by Django 2.1.3 on 2019-07-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0002_servicestatus_friendly_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestatus',
            name='friendly_name',
            field=models.TextField(),
        ),
    ]
