# Generated by Django 2.1.3 on 2019-11-19 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20191119_0339'),
        ('gui', '0003_auto_20190718_1525'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
