from akamai import AkamaiParser
from aws_bucket import AWSBucketParser
from carbon_black import CarbonBlackParser
from cisco_meraki import CiscoMerakiParser
from cortex_xdr import CortexXDRParser
from cybereason import CybereasonParser
from defender_atp import DefenderATPParser
from elasticsearch import ElasticsearchParser
from forcepoint import ForcepointParser
from harfanglab import HarfangLabParser
from imperva import ImpervaParser
from mongodb import MongoDBParser
from netskope import NetskopeParser
from office365 import Office365Parser
from proofpoint_tap import ProofpointTAPParser
from rapid7_idr import Rapid7IDRParser
from reachfive import ReachFiveParser
from sentinel_one import SentinelOneParser
from symantec import SymantecParser
from vadesecure import VadesecureParser
