# Generated by Django 2.1.3 on 2019-04-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Enable or disable the header', verbose_name='Enabled')),
                ('type', models.TextField(choices=[('request', 'Request'), ('response', 'Response')], default='request', help_text='Type of header, request or response')),
                ('action', models.TextField(choices=[('add-header', 'Add'), ('set-header', 'Set'), ('del-header', 'Delete'), ('replace-header', 'Replace name'), ('replace-value', 'Replace value')], default='add-header', help_text='Action to do with the header')),
                ('header_name', models.TextField(default='Cookie', help_text='Concerned header name')),
                ('match', models.TextField(default='matching regex', help_text='')),
                ('replace', models.TextField(default='replacement pattern', help_text='')),
                ('condition_action', models.TextField(choices=[('if', 'If'), ('unless', 'Unless')], default='if', help_text='Facultative condition type of applying the rule')),
                ('condition', models.TextField(default='', help_text='Facultative condition of applying to rule')),
            ],
        ),
    ]
