# Generated by Django 2.1.3 on 2019-08-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0004_auto_20190401_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='match',
            field=models.TextField(default='matching regex', help_text=''),
        ),
        migrations.AlterField(
            model_name='header',
            name='replace',
            field=models.TextField(default='replacement pattern', help_text=''),
        ),
    ]
