# Generated by Django 3.0.5 on 2021-03-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0005_auto_20190829_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='condition_action',
            field=models.TextField(choices=[('', 'Always'), ('if', 'If'), ('unless', 'Unless')], default='', help_text='Facultative condition type of applying the rule'),
        ),
    ]
