# Generated by Django 3.0.5 on 2022-05-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0006_auto_20210317_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='match',
            field=models.TextField(default='matching regex', help_text=''),
        ),
        migrations.AlterField(
            model_name='header',
            name='replace',
            field=models.TextField(default='replacement pattern', help_text=''),
        ),
    ]
